### ISSUE TITLE
Campo obrigatório

### ISSUE THREAD

**Issue by Helfgar** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#104]
Como faço para tornar obrigatório um campo que é opcional?
Preciso mudar o bairro para obrigatório e gostaria de fazê-lo sem ter que mudar o código php.

**Comment by fernandolgccastro** [comment]
Tenho esse interesse também, porém não tenho problemas em mudar o código.

**Comment by Helfgar** [comment]
Não tenho problemas também em mudar no código. O problema vem a ser pelo seguinte: Estou usando esse plugin para um site de um cliente, com o qual não irei mais trabalhar após a conclusão do trabalho, e se eu alterar o código, e o mesmo vir a atualizar, tudo voltará ao de antes. E como plugin não tem child (pelo menos eu desconheço isso)...

**Comment by edsonpecly** [comment]
Qual arquivo para mudar no código?
Comecei a mexer agora com woocommerce e estou "apanhando" disso.

**Comment by renatonascalves** [comment]
Pessoal, o que vocês estão querendo não tem nada a ver com o plugin. Nem sei por que esse issue está aberto.

Segue documetação e exemplo de código que vcs podem usar nos seus sites: https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/#section-2

@claudiosanches Acredito que esse issue pode ser encerrado. =)

**Comment by Helfgar** [comment]
Deu certo. Muito obrigado pela ajuda, Renato.
