### ISSUE TITLE
Preenchimento Automatico

### ISSUE THREAD

**Issue by rfbastos** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#105]
Olá, acabei de instalar o plugin porém quando digito o cep da 404.

Fui no link e recebo o seguinte erro

http://correiosapi.apphb.com/cep/74815755

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Message>Endereço não encontrado!</Message>
</Error>

Nenhum CEP está funcionando, nem mesmo os CEP do exemplo no site 

http://correiosapi.apphb.com/cep/76873274

http://correiosapi.apphb.com/

**Comment by claudiosanches** [comment]
Como expliquei em https://wordpress.org/support/topic/cep-nao-autocompleta-mais/#post-10263813

> 
> Esta opção esta sendo removida deste plugin, pois usa APIs de terceiros e nem sempre funcionam como esperado.
> Eu adicionei esse tipo de ferramenta no plugin dos Correios, lá vai buscar direto na base dos Correios e salvar o resultado no banco de dados do seu site, tornando qualquer consulta posterior mais rápida, além que é mais seguro e sempre atualizado.
> Por esse motivo recomendo parar de usar essa opção que eu devo remover até o meio do ano e começar usar a do plugin dos Correios.
