### ISSUE TITLE
Rest Api v2 não salvando bairro, número e alguns outros dados.

### ISSUE THREAD

**Issue by guilhermelirio** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#106]
Bom dia. Estou tendo uns problemas em salvar alguns dados via rest api do Woocommerce. Segue a lista:

```
email:teste@teste.com.br
password:123456
first_name:Teste
last_name:de Retorno
username:aaaaaa
billing[first_name]:Teste
billing[last_name]:De Retorno
billing[address_1]:Rua Tal
billing[number]:587
billing[address_2]:Apto 201
billing[neighborhood]:Centro
billing[city]:XXXX
billing[state]:ES
billing[postcode]:29000000
billing[country]:BR
billing[email]:teste@teste.com.br
billing[phone]:2799999999
shipping[first_name]:Teste
shipping[last_name]:de Retorno
shipping[address_1]:Rua Tal
shipping[address_2]:Apto 201
shipping[city]:XXXXXX
shipping[state]:ES
shipping[postcode]:29700000
shipping[country]:BR
billing[cpf]:111.111.111-11
```

Retorno que recebo:

`{"id":45,"date_created":"2018-08-10T12:26:48","date_created_gmt":"2018-08-10T15:26:48","date_modified":"2018-08-10T09:26:49","date_modified_gmt":"2018-08-10T12:26:49","email":"teste@teste.com.br","first_name":"Teste","last_name":"de Retorno","role":"customer","username":"aaaaaa","billing":{"first_name":"Teste","last_name":"De Retorno","company":"","address_1":"Rua Tal","address_2":"Apto 201","city":"XXXX","state":"ES","postcode":"29000000","country":"BR","email":"teste@teste.com.br","phone":"2799999999","number":"","neighborhood":"","persontype":"F","cpf":"","rg":"","cnpj":"","ie":"","birthdate":"","sex":false,"cellphone":""},"shipping":{"first_name":"Teste","last_name":"de Retorno","company":"","address_1":"Rua Tal","address_2":"Apto 201","city":"XXXXXX","state":"ES","postcode":"29700000","country":"BR","number":"","neighborhood":""},"is_paying_customer":false,"orders_count":0,"total_spent":"0.00","avatar_url":"https:\/\/secure.gravatar.com\/avatar\/10b9231267e5844f485572e2c3ae14b1?s=96&d=mm&r=g","meta_data":[],"_links":{"self":[{"href":"https:\/\/www.xxxxxxx.com.br\/wp-json\/wc\/v2\/customers\/45"}],"collection":[{"href":"https:\/\/www.xxxxxxxx.com.br\/wp-json\/wc\/v2\/customers"}]}}`

Alguns outros dados também, como pessoa física, jurídica, CNPJ.

Como posso resolver esse problema? Desde já agradeço!

Obs: estou usando o Postman para fazer o teste.

**Comment by rslonik** [comment]
Olá, também estou utilizando a última versão do Woo, do plugin e a REST API v2, e tendo o problema de não conseguir salvar o CPF, por exemplo.

Eu mando a Order:

```
billing:
{
     várias outras propriedades,
     cpf: "18929712088" 
},
```

Retorna:
```
     várias outras propriedades,
     persontype: 'F',
     cpf: '',
     etc...
},
```

**Comment by guilhermelirio** [comment]
Alguma ajuda, @claudiosanches ?

**Comment by rslonik** [comment]
Não sei se te serve, @guilhermelirio, mas por enquanto resolvi mandar o CPF no campo `customer_note`. É um quebra galho.

**Comment by guilhermelirio** [comment]
Interessante @rslonik , mas preciso salvar os demais dados: Bairro, número, etc.

**Comment by rslonik** [comment]
@guilhermelirio encontrei aqui, tem que mandar como `meta_data`:

```
meta_data:
   [ { id: 3931, key: '_billing_cpf', value: '292929292929' },
     { id: 3932, key: '_billing_number', value: '45' },
     { id: 3933, key: '_billing_neighborhood', value: 'Bairro XYZ' } ],
```

**Comment by nunesbns** [comment]
> @guilhermelirio encontrei aqui, tem que mandar como `meta_data`:
> 
> ```
> meta_data:
>    [ { id: 3931, key: '_billing_cpf', value: '292929292929' },
>      { id: 3932, key: '_billing_number', value: '45' },
>      { id: 3933, key: '_billing_neighborhood', value: 'Bairro XYZ' } ],
> ```

Não consegui nem assim. Já tem um método de fazer isso após esses 2 anos?

**Comment by nunesbns** [comment]
> > @guilhermelirio encontrei aqui, tem que mandar como `meta_data`:
> > ```
> > meta_data:
> >    [ { id: 3931, key: '_billing_cpf', value: '292929292929' },
> >      { id: 3932, key: '_billing_number', value: '45' },
> >      { id: 3933, key: '_billing_neighborhood', value: 'Bairro XYZ' } ],
> > ```
> 
> Não consegui nem assim. Já tem um método de fazer isso após esses 2 anos?

Deu certo, é que mudou os valores das keys, não tem mais o underline antes.

meta_data:
   [ { id: 3931, key: 'billing_cpf', value: '292929292929' },
     { id: 3932, key: 'billing_number', value: '45' },
     { id: 3933, key: 'billing_neighborhood', value: 'Bairro XYZ' } ],

**Comment by claudiosanches** [comment]
Na API por padrão só é configurado o retorno, se precisar salvar precisa usar como meta dado igual o @nunesbns mostrou.
