### ISSUE TITLE
Campo Complemento 

### ISSUE THREAD

**Issue by IvanPerfer** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#107]
Olá! É possível deixar o campo "complemento" como opcional?  Pois quando ativado o preenchimento automático do endereço, o valor do frete somente atualiza quando preenchido o complemento e nem todos endereços tem complemento e isso impossibilita o fechamento da venda.
Parabéns! Plugin é show!!!
Grato.

**Comment by claudiosanches** [comment]
Complemento não é algo definitivo para cotar frete, nem com os Correios e nem com outros métodos do WooCommerce, além que complemento nunca é obrigatório, já é opcional por padrão, pode até mesmo configurar isso direto no WooCommerce.

**Comment by IvanPerfer** [comment]
Obrigado pelo feedback. Ainda sou novato com Woocommerce, mas acredito que deve estar ocorrendo algum conflito com o plugin,  WooCommerce Extra Checkout Fields for Brazil (versão 3.6.1), desativei o plugin e no teste mesmo sem digitar nada na área complemento o valor do frete correios apareceu no Checkout. Já com o plugin ativado isso não acontece.
Grato!

**Comment by claudiosanches** [comment]
Estou realizando o mesmo teste e funciona sem nenhum problema, além que o WooCommerce que é quem pega esse campo ou não, se for conflito é com otro plugin.
