### ISSUE TITLE
Mobile não funciona checkout

### ISSUE THREAD

**Issue by Rodibeti** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#108]
Alguém está conseguindo fechar pagamento pelo mobile?
Varios clientes reclamando de não conseguirem.
Verificamos e vimos que reconhece o CEP, mas o campo para escolher o Estado, não funciona.

**Comment by xguiboy** [comment]
também estou com o mesmo problema

**Comment by claudiosanches** [comment]
Corrigido nas versão atual do plugin.
