### ISSUE TITLE
Campo pessoa juridica

### ISSUE THREAD

**Issue by mauroprojetos** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#109]
Como detectar que o cliente selecionou o campo pessoa jurídica?

**Comment by msholl** [comment]
Estou com essa mesma duvida. 
mauroprojetos, você descobriu como fazer?

**Comment by swspcodes** [comment]
Adoraria saber também, principalmente para poder esconder o campo de Razão Social (Empresa) quando está selecionado CPF.

**Comment by claudiosanches** [comment]
@mauroprojetos da para pegar no WooCommerce usando `$order->get_meta( '__billing_person_type' )`. Retorna 1 para CPF e 2 para CNPJ.

@swspcodes isso já foi corrigido.

**Comment by swspcodes** [comment]
Resolvido lindamente
