### ISSUE TITLE
Problema na digitação do telefone com 11 dígitos

### ISSUE THREAD

**Issue by mitmark** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#113]
Prezado
Meu site está com problemas no celular quando preenche 11 dígitos, o mesmo aparece um ? e não conseguimos completar a venda.

**Comment by espimentel** [comment]
Estou com o mesmo problema. Estava cogitando trocar o layout do site, para tentar resolver. Fiz um teste em outro ambiente, porém, o problema volta a aparecer quando habilito o plugin WooCommerce Extra Checkout Fields for Brasil.

Alguém tem alguma novidade sobre esse tema? Não sou programador para conseguir ajudar, mas, se tiver algo que eu possa fazer, me disponho.

**Comment by WesleyGoncalves** [comment]
As duas são antigas, mas parece que essa é uma duplicada #94
