### ISSUE TITLE
CEP não ativa auto complete do endereço

### ISSUE THREAD

**Issue by Cissojr** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#114]
Olá!
Estou com as configurações do campos CEP prontas para executar o autocomplete do endereço, porém, não esta funcionando durante o processo de compra.

Versões:
Woocommerce: Versão 3.4.5
WooCommerce Extra Checkout Fields for Brazil: Versão 3.6.1
WooCommerce PagSeguro: Versão 2.13.1 

Na aba campos do checkout a opção: Habilitar Auto Preenchimento de Endereço: esta habilitada!

Obrigado!
Abs
Cicero

**Comment by csatie** [comment]
A API parece que está fora do ar, mudei para:
`url: '//cep.republicavirtual.com.br/web_cep.php?formato=jsonp&cep=' + cep`

Depois só trocar para address.tipo_logradouro e address.uf

**Comment by MastaBaba** [comment]
When replacing the original URL with the URL above, I get this response in the console:

Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “cep.republicavirtual.com.br”, which could put your confidential information at risk.

**Comment by claudiosanches** [comment]
Essa opção foi removida do plugin. Disponível agora no plugin dos Correios.

**Comment by MastaBaba** [comment]
@claudiosanches can you link to the plugin you refer to?

**Comment by claudiosanches** [comment]
https://wordpress.org/plugins/woocommerce-correios/
