### ISSUE TITLE
Layou comprometido

### ISSUE THREAD

**Issue by FernandoZanch** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#121]
Boa tarde Claudio você poderia me ajudar o layout quebrou e as caixas ficaram fora de lugar como mostra a imagem abaixo acredito que isso é devido a não ter o nome complemento no endereço você poderia me ajudar?
Obrigado.
Fernando.
![11](https://user-images.githubusercontent.com/45404102/49107698-93cf6600-f26d-11e8-842d-21bcf92ad132.jpg)

**Comment by CasperBraske** [comment]
#117

**Comment by FernandoZanch** [comment]
Obrigado pela sua ajuda, mas não alterou fiz varias tentativas com esse css.
Fernando.

**Comment by danielemiliano** [comment]
Tenta colocar esse CSS:

.screen-reader-text {
position: relative!important;
overflow: inherit!important;
height: auto!important;
}

**Comment by kkakko** [comment]
Desculpe minha ignorancia, mas qual arquivo CSS e onde que devo colocar?

**Comment by dinigi** [comment]
> Tenta colocar esse CSS:
> 
> .screen-reader-text {
> position: relative!important;
> overflow: inherit!important;
> height: auto!important;
> }

Adicionar no style.css do woocommerce?

**Comment by dinigi** [comment]
deu certo, muito obrigado @danielemiliano 

Alguem sabe me dizer como consigo alterar o texto dos campos? Quero alterar "Numero" para "Numero da rua/casa"

Muitos clientes colocam o numero de telefone nesse campo

**Comment by igorodrigues** [comment]
@dinigi por favor pode me ajudar, estou com o mesmo erro, como corrigiu o problema?

**Comment by dinigi** [comment]
@igorodrigues tentou adicionar o codigo no styles.css?

**Comment by igorodrigues** [comment]
@dinigi opa, tudo bom?
Então, tentei colar esse código acima no custom code do tema (Uso o ShopKeeper), não deu certo. Em qual arquivo você colocou ele?

**Comment by dinigi** [comment]
@igorodrigues https://imgur.com/a/t0NaJJc

**Comment by igorodrigues** [comment]
Olá @dinigi consegui aqui de outra forma que na vdd acho que funciona bem melhor pra mim.

No caso, foi mexer na ordem first (elementos da equerda), last (elementos da direita) e wide para elementos que pegam a linha toda. Dessa forma conseguir deixar todos os campos alinhados sem mexer em css.

Tinha um bug que o campo neightboor (bairro) e o campo número estavam configurados como form-row-first aí ficava um invadindo o outro e um buraco na linha de baixo. 

De qualquer forma, agradeço demais por ter respondido e me ajudado. :)

**Comment by kkakko** [comment]
Oi @igorodrigues,
Poderia me passar esta dica? Estou com o mesmo problema e o CSS não resolveu.

Te agradeço
:)

**Comment by igorodrigues** [comment]
Oi @dinigi Certo, vou te passar aqui, por favor leve em consideração as imagem que você fez o upload.

O campo CPF esta com a classe form-row-wide, que ocupa a linha toda
O campo CEP esta com a classe form-row-fisrt, que ocupa a primeira coluna(ou a coluna da esquerda)
O campo Cidade está com a classe form-row-last, que ocupa a ultima coluna (ou coluna direita).

O que acontece que fica bugando é a organização de tudo isso ai, pela imagem o campo Bairro, que tem o nome neightboor la no arquivo, esta configurado como form-row-first, sendo que o campo número que está na mesma linha dele também está configurado com essa classe, o certo é o numero esta como first e o bairro como last, fazendo isso eles se alinham.

O arquivo que vc deve fazer as alterações é o Plugins>Woocommerce-extra-fields>includes>class-extra-checkout-fields-for-brazil-front-end.php

Nesse arquivo você vai ver os campos e as classes, só alterar as ordens de acordo como você pretende usar.

:)

**Comment by kkakko** [comment]
Oi, @igorodrigues 

Tentei colocar em ordem, mas não consegui.
Quero colocar nesta ordem:
endereço 1 - endereço 2
número - bairro 
CEP - cidade
estado

mas  o layout não acompanha. Coloquei a linha do código CEP abaixo do endereço 1 e endereço 2, mas não acontece nada.
Desculpe, mas a coisa ficou enrolada. Podes me ajudar?

**Comment by kkakko** [comment]
Já coloquei o campo CEP (billing_postcode) em vários lugares no código, mas no layout, não do mesmo lugar, no máximo do lado direito.

Não consigo colocar o CEP 2 linhas abaixo para que o campo Endereço 2 (billing_address_2) fique na mesma linha que o Endereço 1 (billing_address_1).

Alguma ajuda?

**Comment by gustavohellwig** [comment]
mesmo problema aqui, e somente no biling. no shipping funciona certo.
Como solucionar? vlw !!!

https://jhennykeller.com/checkout/

**Comment by peedrotti** [comment]
Fala pessoal, tudo bem? Estou com o mesmo problema acho... 

No meu todos estão com as configurações certas mas os campos continuam ocupando a linha toda. 
Alguem faz ideia do que pode ser? Uso o tema shopkeeper

![image](https://user-images.githubusercontent.com/20410122/124698811-fbd39780-debf-11eb-9fc2-08e28c34bcd9.png)

**Comment by claudiosanches** [comment]
Agora tem uma opção para ocupar o espaço inteiro que vai resolver esse problema em layouts em colunas.
