### ISSUE TITLE
Não dá refresh no Pedido

### ISSUE THREAD

**Issue by Ditows** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#135]
Se o plugin estiver ativado e mudar o cep na pagina de checkout, o pedido não atualiza, ficando o mesmo valor de frete do cep anterior.
Ao remover o plugin temos algo mais curioso, o calculo funciona ao alterar o cep, mas o plugin do pagseguro mesmo ativo não funciona.

Utilizando ultima versao do wordpress, woocommerce e do plugin

**Comment by Ditows** [comment]
Se o plugin estiver ativado e mudar o cep na pagina de checkout, o pedido não atualiza, ficando o mesmo valor de frete do cep anterior. 
Ao remover o plugin temos algo mais curioso, o calculo funciona ao alterar o cep, mas o plugin do pagseguro mesmo ativo não funciona.

**Comment by Ditows** [comment]
UPDATE: Na verdade, enquanto o número da casa não for digitado, os custos não são calculados.

**Comment by robertofrega** [comment]
Estou vendo aqui que a API que está sendo utilizada não está retornando resultado:
http://correiosapi.apphb.com/cep/01420000

@claudiosanches essa API é controlada por vc de alguma forma?

**Comment by Ditows** [comment]
não que eu saiba

Em Dom, 14 de abr de 2019 18:10, R.Frega <notifications@github.com>
escreveu:

**Comment by claudiosanches** [comment]
Essa ferramenta para o endereço esta sendo removida deste plugin, utilize a que tem no plugin dos Correios.
