### ISSUE TITLE
Famoso problema com as Mascaras no telefone e etc ..

### ISSUE THREAD

**Issue by lucianoitape** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#136]
após atualizações , o campo de telefone ficou sem as mascaras , até já lançaram uma correção extra oficial https://www.jrossetto.com.br/tutoriais/cms/wordpress/correcao-woocommerce-extra-checkout-fields-for-brazil-para-woocommerce-3-5-alinhamento-mascaras/

**Comment by claudiosanches** [comment]
Isso é conflito com jQuery de outros plugins. A biblioteca deste plugin foi alterada a quase dois anos atrás, mas outros plugins ainda usam uma biblioteca para mascaras que é bem antiga e desatualizada e que da conflitos.
