### ISSUE TITLE
Api CEP

### ISSUE THREAD

**Issue by presttec** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#142]
Desenvolvi uma API que consulta o cep dos correios.

E não gostaria de gerar um clone do seu projeto.

Tem como você colocar o recurso no seu formulario?

**Comment by claudiosanches** [comment]
Essa opção foi removida do plugin, no plugin dos Correios tem uma integração direta com o sistema de CEPs dos Correios que funciona bem melhor do que API de terceiros, você pode ativar na aba de "Integrações" nas configurações do WooCommerce depois de instalar o plugin dos Correios.
