### ISSUE TITLE
Erro em listagem de pedidos 

### ISSUE THREAD

**Issue by carlosesposito** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#146]
Na página de pedidos do WooCommerce, na última coluna da listagem aparece: 

=-=-=-=-=-=-=-=-
Warning: Illegal string offset 'number' in /var/www/html/amadispa.com.br/web/amadispa/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php on line 516

Warning: Cannot assign an empty string to a string offset in /var/www/html/amadispa.com.br/web/amadispa/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php on line 516

Warning: Illegal string offset 'neighborhood' in /var/www/html/amadispa.com.br/web/amadispa/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php on line 517

Warning: Cannot assign an empty string to a string offset in /var/www/html/amadispa.com.br/web/amadispa/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php on line 517
=-=-=-=-=-=-=-
(screenshot em anexo)

O gateway utilizado é o Pagar.me.
Pelos testes que fiz, não afetou o processamento do pedido em si. Apenas está atrapalhando o bom uso da listagem dos pedidos. 

![image](https://user-images.githubusercontent.com/31423773/63056534-a272b180-bebe-11e9-862a-61312fd5f854.png)

**Comment by gagustavo** [comment]
Alguém resolveu? Posso abrir um Pull Request para a solução?

**Comment by camasa** [comment]
Olá!
Também estou com o mesmo problema no website de um cliente!
Alguém tem alguma dica de como resolver esse problema?
Obrigado

**Comment by arthurcarlos** [comment]
Olá, por aqui também estou com o problema após atualização do plugin. 

> Alguém resolveu? Posso abrir um Pull Request para a solução?

**Comment by claudiosanches** [comment]
Isso foi corrigido na versão 3.7 do plugin.
