### ISSUE TITLE
Erro Máscara finalização de pedido *** urgente ***

### ISSUE THREAD

**Issue by dankhairalla** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#149]
Nosso ambiente, aceita clientes tanto pessoa fisica quanto jurídica. Esta opção está habilitada nas configurações Campos personalizados de Checkout: –> Exibir Tipo de Pessoa:
No momento de finalizar um pedido, quando o cliente seleciona: Tipo de Pessoa * a máscara está correta, POREM COM ERRO:”Nome da empresa” no endereço de cobrança é um campo obrigatório.
No Brasil quando somos uma pessoa física não temos nome de empresa.
Precisamos corrigir urgentemente esse erro ou se possível indicar como devemos alterar para nosso ambiente não sendo mandatório o campo de empresa quando cliente tipo pessoa física.

att,

@claudiosanches 

Página: https://shopsulmg.com.br/

**Comment by dankhairalla** [comment]
@claudiosanches 

Poderia me auxiliar, por gentileza?!?! É de extrema urgência!!

**Comment by claudiosanches** [comment]
Na configuração no menu personalizar do WooCommerce você provavelmente marcou isso para sempre ser obrigatório.

**Comment by dankhairalla** [comment]
Claudio,
Estou utilizando tanto pra pessoa jurídica e física. Quando seleciono pessoa física no checkout aparece a mensagem de colocar nome de empresa como obrigatório. 
Poderia falar com mais detalhes? Onde se encotra essa opção?


![Screenshot_8](https://user-images.githubusercontent.com/34448564/64717479-cd8af980-d49a-11e9-9b1f-7bf32b2c0ca5.png)

**Comment by claudiosanches** [comment]
O que eu falei é opção do WooCommerce no menu personalizar, se você colocou lá como obrigatório, vai ser obrigatório para tudo, precisa ser opcional.
