### ISSUE TITLE
PHP Warning:  Illegal string offset

### ISSUE THREAD

**Issue by sergiocoser** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#151]
O seguinte erro acontece quando ativo o plugin e tento acessar os pedidos (além de dar "server error" no fechamento pelo checkout transparente pagseguro)

O Plugin precisa de Soapclient ativado?

PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Illegal string offset 'number' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 522
PHP Warning:  Illegal string offset 'neighborhood' in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523
PHP Warning:  Cannot assign an empty string to a string offset in D:\web\localuser\grupoora\www\site\wp-content\plugins\woocommerce-extra-checkout-fields-for-brazil-master\includes\class-extra-checkout-fields-for-brazil-front-end.php on line 523

**Comment by fredperes** [comment]
Estou com o mesmo problema, usando Stripe gateway.

**Comment by cuidados** [comment]
Aqui idem o problema com o pagseguro.

**Comment by cuidados** [comment]
> Aqui idem o problema com o pagseguro.

Resolvi aqui meio que na sorte. O meu Cpanel estava configurado no PHP 7.1, que aqui é a última versão disponível. Alterei para o PHP 7.0 e o problema se resolveu.

Eu tinha atualizado pro 7.1 porque recebi um alerta de que a minha versão do php 5.x estava insegura.

**Comment by sergiocoser** [comment]
Aqui deu certo também. Não sei porque, mas outras lojas em 7.1 funciona normal.

**Comment by cuidados** [comment]
> Aqui deu certo também. Não sei porque, mas outras lojas em 7.1 funciona normal.

Pode estar relacionado com a versão do plugin, do woocommerce ou do WP, vai saber né.

**Comment by sergiocoser** [comment]
Agora queria descobrir como fazer p/ os campos do checkout nao ficarem gigantes (parecem pegar o css do woocommerce padrao)
