### ISSUE TITLE
Problemas versão 3.7.2

### ISSUE THREAD

**Issue by maportugal** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#153]
O combo Tipo de Pessoa já vem habilitado para pessoa física, só que e a máscara do CPF está escondida. O cliente passa direto e recebe mensagem de erro pela falta CPF no final do formulário. Ao mudar o combo para pessoa jurídica e depois novamente para pessoa física o campo do CPF aparece, mas aí novo erro, pede para preencher o nome da empresa para pessoa física!?

**Comment by lucianobc** [comment]
Estou com o mesmo problema. Quando na caixa de seleção com "Pessoa Física" solicita preenchimento do Nome da Empresa

**Comment by jeffermartins** [comment]
Estou com problemas no pagamento com pagseguro.
Nao esta enviando o CPF.
E no formulario do checkout, nao esta exibindos todos os campos

**Comment by claudiosanches** [comment]
Eu não consigo simular esse erro, no caso vai pedir o nome da empresa apenas se você tornou obrigatório no menu personalizar do WordPress.

**Comment by maportugal** [comment]
@claudiosanches isso mesmo! Descobri isso depois de algum tempo.
