### ISSUE TITLE
Como obter os campos para usar em outro plugin?

### ISSUE THREAD

**Issue by diegoweb** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#154]
Estou com esse plugin ativo e gostaria de usar os campos de envio:
CEP
Endereço
Número
Complemento
Bairro
[...]

Qual seria a sintaxe que eu devo usar no meu plugin de frete para puxar esses dados do usuário?

Valeu!

**Comment by claudiosanches** [comment]
Todos esses campos são do WooCommerce, basta usar o CRUD do WooCommerce para pegar isso.
