### ISSUE TITLE
Brazilian Market on WooCommerce não resolveu problema com plugin (melhor envio v2)

### ISSUE THREAD

**Issue by ideiadegenio** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#171]
Tenho um blog onde instalei o WooCommerce. Instalei o plugin MELHOR ENVIO V2 que se trata de uma calculadora de serviço de entrega durante a compra de um produto. Quando coloco o cep do endereço no campo de aperta a tecla calcular ele retorna a mensagem : Nenhuma opção de entrega foi encontrada para sao paulo, São Paulo, 02068-010. Dai instale o plugin Brazilian Market on WooCommerce porém esta mensagem continua aparecendo e não encontro o problema. Ja mexi em tudo na configuração.

**Comment by claudiosanches** [comment]
Cara, não tem nada deste plugin que por padrão resolva qualquer problema com qualquer plugin de Melhor Envio, se alguém desenvolveu isso, deve ser nesse outro plugin e não neste.
