### ISSUE TITLE
Mesmo deletando o plugin ele volta a ser reinstalado 

### ISSUE THREAD

**Issue by osnipassos** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#176]
Olá @claudiosanches tudo certo? Fui usuário por um bom tempo dos seus plugins (muito obrigado) e hoje usamos a integração que não precisa mais.
Mas estranhamente quando deleto os plugins de woocommerce-extra-checkout-fields-for-brazil e woocommerce-correios eles voltam a ser instalados, mesmo eu não tomando uma ação para instalar. Não causa nenhum problema, pois ficam desativados, mas seria bom saber se dá para desabilitar isso.
Já é conhecido? Como desativo esse comportamento?

<img width="1247" alt="Screen Shot 2020-06-26 at 19 39 14" src="https://user-images.githubusercontent.com/711222/85906475-cee8a100-b7e4-11ea-8a3c-580a6e699b07.png">

**Comment by claudiosanches** [comment]
O plugin não consegui ser instalado sozinho assim, provavelmente você tem outra coisa que instala ele, ou talvez algum plugin que exige este plugin como um requerimento, mas como eu falei, não tem codigo neste plugin capaz de fazer ele ser ativado ou instalado sozinho. E se tem algo assim no seu site, não faço ideia do que pode ser, não sei que louco faria algo assim.

**Comment by claudiosanches** [comment]
Se você souber quem foi o responsavel por essa loucura ai, por favor me avise!

**Comment by osnipassos** [comment]
Pois é @claudiosanches, pode me zoar, hehehe, mas é exatamente isso que está acontecendo, por hora está na categoria de bruxaria. Inclusive deletei ontem e já reapareceu hoje novamente.
Relacionado de plugin só tenho WooCommerce e o Mercado Pago payments for WooCommerce e não consegui identificar o gatilho que instala novamente. Não faz parte do tema nem nada.
Isso só acontece nessa instalação aqui ou tem mais alguém?
