### ISSUE TITLE
É possível remover o campo bairro?

### ISSUE THREAD

**Issue by guiqis** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#178]
Tive um problema de formatação com os campos bairro e cidade.

Imagino que é um problema de compatibilidade com o tema. Mas nesse caso, como o bairro é opcional pensei em remover o campo para ver se resolve. É possível fazer isso? 

<img width="928" alt="Captura de Tela 2020-07-26 às 18 07 24" src="https://user-images.githubusercontent.com/15745360/88489504-f610ca80-cf6a-11ea-928c-e739c1472b1d.png">

**Comment by claudiosanches** [comment]
Versão atual do plugin resolve esse problema de formatação, além que tem opção para mostrar todos os campos com largura completa.
