### ISSUE TITLE
Criar coluna na tela de pedidos (admin) informando CPF / CNPJ

### ISSUE THREAD

**Issue by flaviototh** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#188]
Olá, queria saber se há possibilidade de criar uma coluna em Pedidos (admin), especificando se o cliente fez o pedido usando CNPJ ou CPF sem precisar entrar no pedido.

Facilitaria pra mim, pois emito nota quando o cliente faz pedido por PJ, e PF só quando necessário.

Para mim saber a informação, preciso entrar no pedido, isso acaba sendo demorado entrar pedido por pedido!

Até tentei criar uma coluna inserindo código no fuction.php porém não consegui coletar essa informação para duplicar na coluna segue imagem de exemplo https://ibb.co/xS9xWs6

**Comment by claudiosanches** [comment]
Essa feature é muito especifica e você consegue personalizar o WooCommerce para fazer isso.
