### ISSUE TITLE
Campo CEP

### ISSUE THREAD

**Issue by Euejuca** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#2]
Olá Claudio,

Bom dia!

Parabéns pelo seu plugin, funciona muito bem...

A minha unica dúvida é que o meu campo de CEP não esta como primeiro da lista de endereço assim como esta em suas imagens mostradas através dos prints.

Ai o cliente inicia pelo campo endereço, numero, etc ao invés do campo CEP.

O site para verificação é: www.cmasc.com.br/home/

Se puder me dar uma dica de como colocar o campo Cep no topo lhe agradeço.

Att,
Renato

**Comment by felipecm37** [comment]
Boa tarde, o meu plugin apenas nesse site http://brunasalvatori.com.br/lojinha/ e o plugin não auto completa o cep e nem marcação nos numeros, localmente no mesmo tema com os mesmo plugins funciona certo, o que pode ser?
