### ISSUE TITLE
Opções tipo de pessoa em ingles

### ISSUE THREAD

**Issue by sfortus** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#214]
tenho o vosso plugin instalado no meu woocommerce.

O campo person type as opções estão em ingles, como colocar em portugues Individuals ou Legal Person?

**Comment by luizbills** [comment]
Vá na página **Atualizações** no seu WordPress. Provavelmente, faltou baixar a tradução do plugin.

**Comment by sfortus** [comment]
onde posso descarregar a versao com tradução incluida ou só os ficheiros de tradução para portugues ?

**Comment by luizbills** [comment]
A versão em português só está disponivel no português do Brasil e no final da sua página de atualizações você verá um aviso para atualizar ou baixar a tradução. Para português de Portugal ou outros, você precisa baixar o plugin Loco Translate e fazer a tradução manualmente.

**Comment by sfortus** [comment]
obrigado resolveu
