### ISSUE TITLE
checkout problems

### ISSUE THREAD

**Issue by Fernando12M** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#218]
When I go to checkout, the following error appears: The field "Company name" of the billing address is a mandatory field.
The "Add-on" field of the billing address is a required field.

Could you help me to solve this problem?

**Comment by luizbills** [comment]
Isso é um bug que não está relacionado com este plugin, pois nenhum campo "add-on" é criado por este plugin.

**Comment by Fernando12M** [comment]
Quando entrei em contato com o Suporte do Woocommerce fui informado que era por conta do Plugin. Já desinstalei o plugin e instalei novamente e o problema continua.

**Comment by luizbills** [comment]
Qual suporte do woocommerce? Em que site te deram esse suporte?

**Comment by Fernando12M** [comment]
Na plataforma do Wordpress na verdade ... fui informado pelo atendente que o erro constava no plugin, solicitaram o Status do sistema e informaram que identificaram por lá.

**Comment by luizbills** [comment]
Faça o seguinte teste então: desative o **Brazilian Market on WooCommerce** e veja se o problema vai continuar. Se continuar, troque de tema, desative todos os outros plugins (exceto o woocommerce) e reative o Brazilian Market. Tente reproduzir o erro novamente.

**Comment by Fernando12M** [comment]
Ok, irei fazer o teste. Irei demorar um pouco para dar um retorno sobre o resultado.

**Comment by luizbills** [comment]
Se você fez os testes da maneira que eu pedi (sem o Brazilian Market ativado) e os erros continuaram, então é problema com outro plugin seu. Você precisa contratar um profissional para te auxiliar.

**Comment by C4rL0sM4gn0** [comment]
@Fernando12M conseguiu resolver? Estou com o mesmo problema...

**Comment by claudiosanches** [comment]
Fixed in the latest version of this plugin.
