### ISSUE TITLE
Tipo de Pessoa Fisica e Juridica a caixa combo aparece apenas um pedaço

### ISSUE THREAD

**Issue by adinstar** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#219]
![image](https://user-images.githubusercontent.com/98432832/181843083-b1a7f7ff-025e-434e-a20d-ae1e1db8bfa8.png)

**Comment by luizbills** [comment]
Isso é bug do seu tema, não do plugin. Caso não tenha conhecimento técnico, contrate um desenvolvedor que isso é resolvido facilmente.
