### ISSUE TITLE
Acrescentar item na lista "Sexo"

### ISSUE THREAD

**Issue by delosinfo** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#222]
Pela legislação atual é necessário acrescentar á opção "Não quero informar" no tipo de sexo.
Isso será implantado?

**Comment by luizbills** [comment]
Você (ou um desenvolvedor) pode alterar facilmente usando o hook `woocommerce_billing_fields` com prioridade igual ou maior que 11.
