### ISSUE TITLE
Remover máscara ao submeter (salvar sem máscara)

### ISSUE THREAD

**Issue by igordisco** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#223]
Olá! Gostaria de salvar o campo de telefone (99) 99999-9999 sem máscara no banco de dados.

Para enviar via webhook para whatsapp é mais acertivo.

Cheguei a tentar .unmask() mas não funcionou.

Onde que eu devo fazer alguma alteração?

**Comment by claudiosanches** [comment]
É melhor tratar isso quando for enviar o Webhook por exemplo, você pode remover tudo que não é número.
Pode usar a função `wc_sanitize_phone_number()` do WooCommerce pra isso.
