### ISSUE TITLE
Shortcode 

### ISSUE THREAD

**Issue by jfernando1599** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#227]
Como posso criar um shortcode do cpf, rg e do numero da casa? Estou usando um plugin para assinatura que gera um contrato no final do pedido. Ele pede o shortcode. Alguem pode me ajudar?

**Comment by claudiosanches** [comment]
É tudo meta dado no WooCommerce. Só usar `$order->get_meta( '_billing_cpf` )` para o CPF por exemplo e assim por diante.
