### ISSUE TITLE
Quando seleciono no menu Drop Down Pf/PJ não muda

### ISSUE THREAD

**Issue by lumiche1** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#231]
Bom dia,

Estou usando a implementação, porém quando seleciono o campo PF/PJ o menu não muda para os campos selecionados sendo que aparecem os 2 campos para digitar como na foto, onde qunado você sleeciona um o outro some e vice versa. Parece que ele perdeu uma formatação ou algo assim. alguém poderia ajudar ?

![Sem título](https://github.com/claudiosanches/woocommerce-extra-checkout-fields-for-brazil/assets/136484732/f695c6d4-6c6f-476d-bdeb-c744a12d3a7c)

**Comment by claudiosanches** [comment]
Isso funciona sem problema na versão mais recente do plugin que lancei hoje.
