### ISSUE TITLE
Compatibilidade com High-Performance Order Storage (HPOS)

### ISSUE THREAD

**Issue by felipelguimaraes** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#235]
Já faz algum tempo que o HPOS começou a ser lançado em novos, e acho que agora já está mais seguro para implementar em sites antigos.
O ganho de performance em algumas lojas seria significativo.

Alguém que já mexeu no plugin mais a fundo tem um overview do que precisaria ser alterado?

**Comment by tiagopapile** [comment]
Fiz a alteração necessária pra marcar o plugin como compatível com HPOS.

Detalhes nesse PR #237

**Comment by r-martins** [comment]
Confesso que estou apanhando um pouco pra conseguir resgatar o valor salvo em _billing_number por exemplo.
`$this->order->get_meta('_billing_number')` funciona sem HPOS ativado, mas não com ele ativado.

Alguma dica?
