### ISSUE TITLE
Campo CPF nao é obrigatório mesmo marcado como obrigatório

### ISSUE THREAD

**Issue by igoragatti** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#244]
Mesmo após marcar o CPF como obrigatório nas configs ao realizar checkout não está deixando-o obrigatório.

**Comment by igoragatti** [comment]
Pelo que vi tem um PR já resolvendo esse problema.

**Comment by claudiosanches** [comment]
Corrigido na versão 4.0.2.
