### ISSUE TITLE
Estou com problema na finalização das vendas, o CPF e o Bairro não está aparecendo.

### ISSUE THREAD

**Issue by Claudiochss** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#248]
Olá Cláudio! 
Tudo bem ? 

Estou com problema com meu Checkout, pois a função CPF e Bairro não está aparecendo.
Ja baixei o plugin Brazilian Market on WooCommerce, só que mesmo assim ainda não aparece. 
Verifiquei todas as atualizações mesmo assim não resolveu. 
Não sei o que fazer mais, será que vocês conseguem me ajudar ? 
Desde de já muito obrigado

**Comment by claudiosanches** [comment]
Isso no caso é o novo bloco de checkout do WooCommerce que é novo e ainda não é suportado por este plugin. Você pode remover o bloco e adicionar novamente o shortcode `[woocommerce-checkout]` para fazer isso funcionar.

Entretanto, se quiserem me ajudar atualizar o plugin logo para adicionar campos nos blocos, vocês podem contribuindo no meu Apoia.se: https://apoia.se/claudiosanches

Atualmente não tem nem 25 pessoas contribuindo, aumentando esse número eu iria conseguir dedicar mais tempo para fazer atualizações de forma mais rápida.
