### ISSUE TITLE
Adicionar Campo Mensagem

### ISSUE THREAD

**Issue by furlann** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#32]
Olá, parabéns pelo plugin, eu preciso adicionar um campo de mensagem, tem como eu inserir ?

**Comment by renatonascalves** [comment]
@furlann Não entendi! Podes elaborar?

**Comment by eddie7** [comment]
Como faço para adicionar um campo a mais no checkout. Eu preciso um campo para adicionar o número de um serial ou simm card.

**Comment by renatonascalves** [comment]
@eddie7 Existem alguns plugins no repositório do WordPress  que permite adicionar campos no Checkout. Recomendo pesquisar lá!

Acho que seu pedido, e o do @furlann, não é relacionado a esse plugin. Ele serve outro propósito. :)
