### ISSUE TITLE
trocar classe form-row dos campos

### ISSUE THREAD

**Issue by davirs** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#38]
O módulo é excelente e funciona corretamente. Só preciso de uma dica.

Meu form de checkout tem alguns campos escondidos, portanto tem classes com first e last no lugar errado.
Gostaria de saber qual arquivos eu faço essas alterações para substituir a classe form-row-first ou form-row-last quando necessário..

Obrigado

**Comment by claudiosanches** [comment]
Da mesma forma que troca no WooCommerce.

**Comment by davirs** [comment]
e qual seria? Desculpe soar grosseiro, mas se soubesse não tinha pedido..

Obrigado pela atenção

**Comment by claudiosanches** [comment]
@davirs este plugin adiciona campos no checkout usando as ferramentas que o WooCommerce já disponibiliza para manipular os campos, se tiver dúvida ou problema específicos com este plugin, vou ficar feliz em ajudar, caso o contrário você deveria usar o fórum de suporte do WordPress Brasil: http://br.wordpress.org/support/
