### ISSUE TITLE
Última versão do plugin não carrega os scripts necessário na 'minha conta'

### ISSUE THREAD

**Issue by felipekraus** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#39]
Oi Claudio,

Na última versão do plugin alguns métodos foram revisitados como o 'enqueue_scripts' na linha 72 do arquivo 'class-wc-ecfb-front-end.php' que agora possui um i no início que faz com que os scripts não sejam carregados em 'minha conta'.

Segue uma possível solução:
if ( !is_checkout() && !is_account_page()) {
	return;
}

Obrigado!

**Comment by claudiosanches** [comment]
Já esta sendo corrigido na próxima versão.
