### ISSUE TITLE
Pagseguro captura campo Telefone como se fosse Campo Celular 

### ISSUE THREAD

**Issue by frontfelipe** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#40]
Estou utilizando o plugin do PagSeguro e ele captura o campo Telefone (Checkout) e insere como se fosse Celular na finalização de pagamento (PagSeguro)

**Comment by frontfelipe** [comment]
Como posso corrigir esta inversão?

**Comment by claudiosanches** [comment]
No plugin do PagSeguro é tratado apenas o telefone e passado para a API do PagSeguro no campo `phone`, nada de celular é utilizado.

**Comment by frontfelipe** [comment]
Ele só esta invertendo a captura dos campos, no caso ele pega do campo celular e usa como se fosse Phone...

**Comment by claudiosanches** [comment]
Mas ele não pega qualquer dado de celular, apenas do campo de telefone.

**Comment by frontfelipe** [comment]
Tenho o cadastro para finalizar a conta e la tem campo Celular e Telefone, na hora que finaliza a compra, o plugin captura o campo celular ao inves de pegar o do telefone

**Comment by claudiosanches** [comment]
O código é aberto, basta ler e ver que tem tem absolutamente nada pegando campo de celular em nenhum lugar do plugin: https://github.com/claudiosanches/woocommerce-pagseguro
Basta me mostrar onde pega o campo de celular que eu arrumo, sem nenhum problema.
