### ISSUE TITLE
Campos nome e sobrenome

### ISSUE THREAD

**Issue by taguada** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#43]
Olá, tudo bom?

Está tudo funcionando a minha integração com o **WooCommerce PagSeguro** e **WooCommerce Extra Checkout Fields for Brazil**. A questão é que os campos **Nome** e **Sobrenome** no momento de finalizar a compra, parece que o CSS está com problema.

Não sou bom nesse assunto, mas me parece que está faltando **input-field** na **class**, pois ao inspecionar o código no Chrome, eu comparei com os demais campos e esse item está faltando, e quando adicionado no campo **Nome**, por exemplo, ele corrigi o layout.

Um adicional é que fiz uma instalação limpa do Wordpress, WooCommerce e os plugins em questão, mesmo assim permaneceu o problema. Uso um tema (https://themeforest.net/item/venedor-wordpress-woocommerce-theme/7807674?s_rank=1) para o **WooCommerce**. Então se puder me informar que esse problema não tem relação alguma com o seu plugin. Fiquei na dúvida, pois quando desabilitado o plugin **WooCommerce Extra Checkout Fields for Brazil** os campos **Nome** e **Sobrenome** ficam no layout correto.

Por favor, poderiam revisar essa questão ou me informar se existe algo que possa fazer aqui? Abaixo estão as imagens para melhor entendimento.

![css](https://cloud.githubusercontent.com/assets/25000051/21757889/52022e3e-d61c-11e6-8980-b76a712305bc.PNG)
![tela](https://cloud.githubusercontent.com/assets/25000051/21757890/5202abd4-d61c-11e6-9832-a556fe5075dd.PNG)

**Comment by taguada** [comment]
Desculpe, esqueci de comentar que uso um tema (https://themeforest.net/item/venedor-wordpress-woocommerce-theme/7807674?s_rank=1) para o **WooCommerce**. Então se puder me informar que esse problema não tem relação alguma com o seu plugin. Fiquei na dúvida, pois quando desabilitado o plugin **WooCommerce Extra Checkout Fields for Brazil** os campos Nome e Sobrenome ficam no layout correto.

**Comment by claudiosanches** [comment]
Isso é com o seu tema, se esta usando os plugins atualizados e o tema não esta aplicando o CSS como deveria, então é porque falta algo no tema.
