### ISSUE TITLE
Campos em inglês

### ISSUE THREAD

**Issue by vicenterusso** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#45]
Vi este [tópico](https://wordpress.org/support/topic/traducao-para-o-portugues-como-fazer/), mas não me ajudou.

Reparei que o .pot tambem [não tem nada traduzido](http://i.imgur.com/XZhRd1X.png).

Em outro [link](https://translate.wordpress.org/projects/wp-plugins/woocommerce-extra-checkout-fields-for-brazil/language-packs), achei a traducao do plugin para pt_BR. No entanto, não consegui fazer funcionar. Afinal, nao era pra já vir a traducao junto neste repo? Como ativar a tradução?

Meu wordpress está em portugues do brasil. 

Valeu

**Comment by renatonascalves** [comment]
A tradução é automática! Carrega do repositório de traduções do WordPress. Acredito que a tradução deve está disponível em Atualizações, abaixo do Painel.
