### ISSUE TITLE
Separar opção de Data de Nascimento e Sexo

### ISSUE THREAD

**Issue by wshossein** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#46]
Nos settings do plugin há a opção "Exibir Data de Nascimento e Sexo" e ela habilita a data de nascimento e o sexo da pessoa mas não é possível habilitar só o sexo ou só a data de nascimento. Isso é importante em negócios onde o sexo do cliente não importa e quando estamos falando de sexo (que deveria estar descrito como gênero) pode-se criar alguns problemas de inclusão quando limitamos a apenas "masculino" e "feminino".

**Comment by claudiosanches** [comment]
Pode você mesmo então criar um campo para data de nascimento.
