### ISSUE TITLE
Número e Bairro não aparecem no resumo dos Endereços (Minha Conta)

### ISSUE THREAD

**Issue by gabrielefernandes** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#47]
Cláudio, apesar das alterações (log de mudanças: 3.4.3 - 2016/03/20 e 3.4.4 - 2016/06/20), por alguma razão **o número e o bairro** não aparecem ao entrar na "minha-conta" / "Enderecos". Consequentemente, não aparecem também no email que o vendedor recebe com o resumo do pedido.

Incluí no `woocommerce/myaccount/my-address.php` e não funcionou:

```
<address>
	<?php
		$address = apply_filters( 'woocommerce_my_account_my_address_formatted_address', array(
			'first_name'  => get_user_meta( $customer_id, $name . '_first_name', true ),
			'last_name'   => get_user_meta( $customer_id, $name . '_last_name', true ),
                        'company'     => get_user_meta( $customer_id, $name . '_company', true ),
                        'address_1'   => get_user_meta( $customer_id, $name . '_address_1', true ),
			'address_2'   => get_user_meta( $customer_id, $name . '_address_2', true ),
                        'number'      => get_user_meta( $customer_id, $name . '_number', true ),
                        'neighborhood'      => get_user_meta( $customer_id, $name . '_neighborhood', true ),
			'city'        => get_user_meta( $customer_id, $name . '_city', true ),
			'state'       => get_user_meta( $customer_id, $name . '_state', true ),
			'postcode'    => get_user_meta( $customer_id, $name . '_postcode', true ),
			'country'     => get_user_meta( $customer_id, $name . '_country', true )
		), $customer_id, $name );
			$formatted_address = WC()->countries->get_formatted_address( $address );                     
			if ( ! $formatted_address )
				_e( 'You have not set up this type of address yet.', 'woocommerce' );
			else
				echo $formatted_address;           
	?>
</address>
```

**Comment by gabrielefernandes** [comment]
Olá @claudiosanches. Consegue me ajudar com essa questão? Obrigada.

**Comment by claudiosanches** [comment]
Não tem necessidade de incluir isso no arquivo, porque o plugin já usa o filtro para adicionar.
O template é personalizado?
Já tentou com um tema padrão?

**Comment by gabrielefernandes** [comment]
O tema é personalizado sim. Eu comprei no Themeforest e o autor diz que é 100% compatível com o Woocommerce.
Eu troquei os labels, renomeando um outro campo (billing_address_2) para mostrar "Bairro" e deletando o 'billing_neighborhood' - o que aparentemente tinha resolvido o meu problema. Porém, surgiu outro, pois o checkout transparente do pagseguro exige que o 'billing_neighborhood' esteja preenchido para concluir a compra.
**Como posso fazer para o pagseguro transparente aceitar o 'billing_address_2' ao invés do 'billing_neighborhood'?**

Se não for possível, eu voltei a estaca zero novamente. Então retorno com a pergunta:
**Como posso mostrar o ['value'] do 'billing_neighborhood' no "Minha conta/Endereços" e no email após a compra do produto?**
Tks.

**Comment by claudiosanches** [comment]
Se esta usando esse plugin, não deveria estar removendo ou trocando os campos do plugin, o que vai dar mais problemas.
Acho que seria mais simples remover as suas modificações e testar com outro tema para conseguir falar com o autor do tema se tem problema ou não.
O autor do tema esta dizendo que é "100% compatível" e eu estou dizendo que este plugin funciona 100% sem problema com qualquer tema compatível.

**Comment by gabrielefernandes** [comment]
Sim, o meu tema modificou algo que tirou o número e o bairro do resumo do Endereço.
A solução foi mais simples do que eu imaginei...
Inseri o código abaixo no `functions.php` do meu child theme e resolveu meu problema:

```
function custom_address_formats( $formats ) {
    $formats[ 'default' ]  = "{name}\n{address_1}, {number}, {address_2}\n{neighborhood}\n{city} / {state}\n{postcode}";   
    return $formats;
}
add_filter('woocommerce_localisation_address_formats', 'custom_address_formats');
```
