### ISSUE TITLE
Campo de seleção de sexo

### ISSUE THREAD

**Issue by lmpaiva** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#48]
Olá,

Não sou programador, sei apenas um pouco de html e css.

Gostaria de tentar resolver um problema que estou tendo dificuldades para solucionar.

Utilizo um theme para woocommerce chamado Despacho, da Yithemes.

Instalei o plugin para informações extras no checkout mas não está permitindo selecionar o sexo. A caixa simplesmente não aparece.

Segue imagens.

![erro plugin](https://cloud.githubusercontent.com/assets/16328786/23571839/28531c12-004a-11e7-9a14-affbf6e2731b.png)

Att.

**Comment by claudiosanches** [comment]
Esta ai na tela a solução, o tema esta aplicando `visibility: hidden;` para todos os campos de select do checkout.
Problema é no tema e não no plugin, pode trocar de tema ou arrumar o CSS.
