### ISSUE TITLE
Posição dos campos

### ISSUE THREAD

**Issue by brunocard** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#50]
Boa noite amigo td bem? Os campos não estão distribuídos de forma muito amigável no meu tema, alguns estão quebrando pra linha de baixo sendo que poderia estar um ao lado do outro e gostaria tb de deixar o campo CEP antes do endereço para que possa ser preenchido primeiro e autocompletar o endereço. qual seria o arquivo onde eu poderia fazer essas edições? 

Muito obrigado pela atenção.
A propósito parabéns pelo seu trabalho ficou muito bom o plugin.

**Comment by brunocard** [comment]
![finalizar compra compra na cidade - google chrome](https://cloud.githubusercontent.com/assets/27520005/25056894/2ef4fca2-2142-11e7-9944-d084d4a15e5e.jpg)

**Comment by claudiosanches** [comment]
Já recebeu correções para funcionar melhor com a organização no WooCommerce 3.0.
Recomendo atualizar tudo.
