### ISSUE TITLE
Data de nascimento e Sexo desconfigurando formulário

### ISSUE THREAD

**Issue by ravimartins** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#51]
Olá Claudio, tudo bem?

Notei que após a última atualização, quando habilito a configuração para mostrar a Data de Nascimento e Sexo o formulário de cadastro fica desconfigurado, sai da ordem. Queria saber se é algo que já foi notado e está sendo tratado ou teria que verificar alguma coisa no meu tema?

Estou usando GeneratePress e WooCommerce na versão 3.0.
Caso queira checar pessoalmente, o site é https://lumisemijoias.com.br

Abraço.

**Comment by claudiosanches** [comment]
Já respondi isso para você no fórum.
