### ISSUE TITLE
Validação de CNPJ

### ISSUE THREAD

**Issue by matheustnt** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#52]
Olá Cláudio, ao tentar finalizar uma compra, ocorreu um erro de `CNPJ é inválido`, porém eu estava usando um CNPJ que já havia sido testado e funcionado em outras versões do plugin. Visitei o suporte e vi que era um erro que vinha acontecendo com outras pessoas. Ao revisar o código, percebi que no arquivo `includes/class-extra-checkout-fields-for-brazil-formatting.php` , função `is_cnpj`, continha o seguinte:
```
if ( $cnpj[ ++$t ] !== ( $d = ( ( 10 * $d ) % 11 ) % 10 ) ) {
	return false;
}
```
No meu processo de depuração, pude chegar a conclusão que a causa do erro é que o conteúdo de  `$cnpj[ ++$t ]` é do tipo `string` e o resultante de  `( $d = ( ( 10 * $d ) % 11 ) % 10 )` é do tipo `integer`, e ao usar o comparador `!==`, o comparador verifica o valor e a tipagem da expressão/variável. 
Ao retornar esse comparador para `!=` a validação voltou a funcionar normalmente.

**Comment by claudiosanches** [comment]
@matheustnt obrigado por reportar isso.
