### ISSUE TITLE
Plugin Desconfigurando Layout do Checkout

### ISSUE THREAD

**Issue by ceroni** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#53]
Boa tarde! 
Gostaria de saber se tem alguma correção para esse tipo de problema, no qual o campo endereço de e-mail não fica sobre a caixa de preenchimento do mesmo e o campo Notas do pedido fica deslocado do local original.

Essas são as imagens dos problemas:

Problema 01: https://uploaddeimagens.com.br/imagens/imagem_01-png--6
Problema 02: https://uploaddeimagens.com.br/imagens/imagem_02-png--4

Obrigado, aguardo a sua ajuda!

**Comment by claudiosanches** [comment]
WooCommerce removeu algumas coisas que limpam float dos campos e por isso acontece.
Você pode corrigir isso dai usando CSS, é bem simples, mas como você me mostrou apenas screenshots, não é possível te dizer exatamente qual CSS precisa usar, de qualquer forma é fácil, boa sorte.
