### ISSUE TITLE
Permitir apenas informar números e S/N no campo número

### ISSUE THREAD

**Issue by Odacir27** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#54]
No campo número está aceitando entrada alphanumérica, e tem clientes que informam outra coisa no campo número.

Fazendo validação para aceitar apenas números e S/N, ou SN, vai resolver mais este problema.

**Comment by claudiosanches** [comment]
@thiagogsr nunca fácil usar campos de número e validação apropriada.

**Comment by thiagogsr** [comment]
@claudiosanches o campo número não tem máscara e é do tipo `text`.

@Odacir27 como não existe uma convenção/padrão sobre isso, eu não vejo isso como um problema.

**Comment by claudiosanches** [comment]
@thiagogsr não esta alterando por JS?

**Comment by thiagogsr** [comment]
Esse campo não @claudiosanches

**Comment by claudiosanches** [comment]
@Odacir27 então não tem nenhuma validação nisso cara.
Se tiver, é algum método de pagamento que esta recebendo o campo e dando o erro, mas não tem neste plugin.

@thiagogsr valeu.

**Comment by Odacir27** [comment]
Oi @claudiosanches, não sei se me fiz entender, mas o problema, por exemplo, é que um cliente, em vez de preencher o número, coloca ali o bairro, ou cidade, coisa que não tem nada a ver.... Por isso a intenção de limitar o campo NÚMERO do enderenço, a aceitar apenas dígitos e o S/N para sem número.

**Comment by claudiosanches** [comment]
Ahh não, tem o label dizendo que é número, colocar limitação nesse campo pode deixar as coisas mais complicadas.
Além que se o cliente não preencheu corretamente os campos, basta você entrar em contato com ele, além de explicar isso na página de termos.

**Comment by thiagogsr** [comment]
Concordo com @claudiosanches, como falei, não existe uma regra definida sobre esse campo, cada um informa de um jeito, restringir os caracteres pode trazer mais problemas como conversão de clientes que se estressam porque não conseguem colocar o dado real.

**Comment by Odacir27** [comment]
Beleza Cláudio e Thiago, obrigado pelas colocações....É complicado e o que vcs dizem tb faz sentido.
Eu tinha uma loja, pra um amigo, que já tinha sido feita em Oscommerce, migrei pra prestashop 1.alguma coisa, e agora foi pra Woo Commerce.... No Prestashop não tinha o campo número separado, era sempre uma encrenca, volta e meia não informavam número..... Agora no Woo Commerce, tudo certinho com número, e o primeiro pedido real na loja, o sujeito informou o bairro dentro do campo número........ Murph.

Novamente, obrigado pessoal. Abraço!
