### ISSUE TITLE
Erro no checkout - nao reconhece endereco

### ISSUE THREAD

**Issue by fffcion** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#55]
Apos preencher todos os campos no checkout, recebo a resposta de preencha um endereco, sem erro nos logs ou no console; jah viu isso acontecer? alguma pista?

http://new.somdecristal.com.br/checkout/

![screen shot 2017-05-20 at 15 54 47](https://cloud.githubusercontent.com/assets/17616616/26278592/baa54f06-3d74-11e7-9f3b-755df1a1848f.png)

**Comment by claudiosanches** [comment]
Acontece apenas com quando este plugin esta ativado?

**Comment by claudiosanches** [comment]
Acabei de testar e funcionou sem problema.

**Comment by rhenandomingos** [comment]
Boa noite @fffcion, estou encontrando o mesmo problema em um website que estou implementando. Acessei seu website e verifiquei que conseguiu resolver. Poderia me dar uma luz sobre esta questão?

**Comment by vjdarts** [comment]
Estou com este mesmo problema.


como corrige?

**Comment by AlexHar** [comment]
@vjdarts Não sei se é o seu caso mas eu uso o outro plugin do "Checkout Field Editor for WooCommerce" e nesse plugin tem a opção de "Reset to default fields" isso resolveu meu problema. Creio que não seja problema aqui do plugin do Claudio.

**Comment by Ramon345** [comment]
Pessoal, boa noite, 
estou com esse mesmo problema e não estou conseguindo resolver. Por favor alguem poderia me ajudar? Preciso de mais resolver esse erro.

![Captura de tela 2024-04-05 191414](https://github.com/claudiosanches/woocommerce-extra-checkout-fields-for-brazil/assets/166179665/f8f1a9cd-375e-4dd9-b90e-461af11950ce)

**Comment by Ramon345** [comment]
Quem puder me ajudar eu agradeço de mais!!

**Comment by rodrigorochanl** [comment]
Tenta deixar a opção brasil já fixo e aparecendo no formulario. , acho que
consegui resolver assim. Que eu me lembre, desta forma foi solucionado.





Em sex., 5 de abr. de 2024 às 19:15, Ramon345 ***@***.***>
escreveu:

**Comment by Ramon345** [comment]
Muito obrigado! @vjdarts vou ajustar e te falo, estou desesperado para resolver isso. Muito obrigado memso!

**Comment by Ramon345** [comment]
@vjdarts, eu deixei fixado o país mas agora está solicitando número e barro, mas está tudo preenchido corretamente. Poderia verificar se você já teve esse problema? por favor

![image](https://github.com/claudiosanches/woocommerce-extra-checkout-fields-for-brazil/assets/166179665/534a15b8-2ca7-4dcc-8d6c-201c049db444)

**Comment by rodrigorochanl** [comment]
tenta deixar desta forma.

[image: image.png]
[image: image.png]
este é o site do app.
https://br.wordpress.org/plugins/woo-checkout-field-editor-pro/

nota os campos que dá erro você consegue reformular aqui.

Brother, eu resolvi este problema ha muito tempo, então me lembro muito
bem, mas este é o caminho.

Tomara que de tudo certo ai contigo.

Não esqueça de seguir no insta. sempre coloco la nos stories varios
problemas de e-commerce. qualquer coisa me chama la tbm.

www.instagram.com/rodrigorocha.nl





Em sex., 5 de abr. de 2024 às 20:33, Ramon345 ***@***.***>
escreveu:
