### ISSUE TITLE
Dados ignorados em 'Post' via API do WooCommerce

### ISSUE THREAD

**Issue by augustoveiras** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#56]
Caro Claudio Sanches e demais colegas,

Estou tentando enviar dados de uma planilha do Google Sheet para uma loja WooCommerce (via API 'Post'), mas venho enfrentando dificuldades com os campos específicos do plugin 'WooCommerce Extra Checkout Fields for Brazil'. Os demais campos (padrão do WooCommerce) funcionam normalmente.

Segue abaixo o código (Google Script) que estou usando para enviar dados para a loja:

`var novoCliente = {
    'customer': {
      'email': 'jose.silva@empresa.com.br',
      'password': '12345678',
      'username': 'jose.silva',
      'first_name': 'José',
      'last_name': 'Silva',
      'billing_address' : {
        'first_name': 'José',
        'last_name': 'Silva',
        'company':'Empresa',
        'address_1':'Av. Rio Branco',
        'address_2':'Sala 805',
        'city':'Florianópolis',
        'state':'Santa Catarina',
        'postcode':'88015-201',
        'country':'Brasil',
        'email': 'jose.silva@empresa.com.br',
        'phone' : '(48) 3025-0000',
        'persontype':'J',
        'cpf' : '000.000.001-01',
        'rg' : '1.234.567',
        'cnpj' : '99.888.999-0001/88',
        'ie' : '000000',
        'birthdate' : '01/01/1980',
        'sex' : 'M',
        'number' : 533,
        'neighborhood' : 'Centro',
        'cellphone' : '(48) 99898-0000'
      }
    }
  };`

`var postOptions = {
    'method': 'post',
    'contentType': 'application/json',
    'payload': JSON.stringify(novoCliente),
    'muteHttpExceptions': true
  };`

`UrlFetchApp.fetch(urlLoja+'/wc-api/v3/customers?consumer_key='+chaveUsuario+'&consumer_secret='+segredoUsuario , postOptions);`

Ao executar o código acima, essa é a resposta que recebo do 'post':

`{
  "customer": {
    "id": 44,
    "created_at": "2017-06-25T04:12:29Z",
    "last_update": "2017-06-25T01:12:30Z",
    "email": "jose.silva@empresa.com.br",
    "first_name": "José",
    "last_name": "Silva",
    "username": "jose.silva",
    "role": "customer",
    "last_order_id": null,
    "last_order_date": null,
    "orders_count": 0,
    "total_spent": "0.00",
    "avatar_url": "https://secure.gravatar.com/avatar/188bb2a69fc7e9b34a502721ee6ee3bc?s=96",
    "billing_address": {
      "first_name": "José",
      "last_name": "Silva",
      "company": "Empresa",
      "address_1": "Av. Rio Branco",
      "address_2": "Sala 805",
      "city": "Florianópolis",
      "state": "Santa Catarina",
      "postcode": "88015-201",
      "country": "Brasil",
      "email": "jose.silva@empresa.com.br",
      "phone": "(48) 3025-0000",
      "persontype": "F",
      "cpf": "",
      "rg": "",
      "cnpj": "",
      "ie": "",
      "birthdate": "",
      "sex": "",
      "number": "",
      "neighborhood": "",
      "cellphone": ""
    },
    "shipping_address": {
      "first_name": "",
      "last_name": "",
      "company": "",
      "address_1": "",
      "address_2": "",
      "city": "",
      "state": "",
      "postcode": "",
      "country": "",
      "number": "",
      "neighborhood": ""
    }
  }
}`

Repare que todos os campos inseridos pelo plugin foram ignorados pela API do WooCommerce:

`    "persontype": "F",
      "cpf": "",
      "rg": "",
      "cnpj": "",
      "ie": "",
      "birthdate": "",
      "sex": "",
      "number": "",
      "neighborhood": "",
      "cellphone": ""`

Como devo proceder para enviar esses dados para o WooCommerce?

Ressalto que, nos casos de clientes cadastrados direto na plataforma WooCommerce, eu consigo ler os dados do plugin (persontype, cpf, rg, cnpj, etc.) pela WC-API sem o menor problema.

O que estou fazendo de errado? Alguém já enfrentou esse problema? Alguém tem alguma luz?

Obrigado!

Augusto Veiras

**Comment by claudiosanches** [comment]
Não vai provavelmente suportar bem a API depreciada no WooCommerce, vai funcionar apenas com a nova API na versão v1 ou v2, com esses é certeza que vai funcionar tudo ok.
Sem dizer que a API que você esta usando vai deixar de fazer parte do WooCommerce em Junho do ano que vêm.

**Comment by augustoveiras** [comment]
Olá, Claudio!

Primeiramente, obrigado pelo breve retorno e pelas orientações.

Adaptei o meu código para utilizar as versões v1 e v2 da API, conforme sua orientação, mas continuo com o mesmo problema. Seguem abaixo os detalhes:

1. Troquei a chamada para a API pelos seguintes códigos:
`UrlFetchApp.fetch(urlLoja+'/wp-json/wc/v1/customers?consumer_key='+chaveUsuario+'&consumer_secret='+segredoUsuario , postOptions);`
e
`UrlFetchApp.fetch(urlLoja+'/wp-json/wc/v2/customers?consumer_key='+chaveUsuario+'&consumer_secret='+segredoUsuario , postOptions);`

2. Em ambos os casos, troquei a chave `'billing_address'` por apenas `'billing'` e, mesmo assim, continuo obtendo os seguintes resultados:

Para API v1:
`{"id":51,"date_created":"2017-06-27T03:52:31","date_modified":"2017-06-27T00:52:31","email":"jose.silva@empresa.com.br","first_name":"Jos\u00e9","last_name":"Silva","username":"jose.silva","last_order":{"id":null,"date":null},"orders_count":0,"total_spent":"0.00","avatar_url":"https:\/\/secure.gravatar.com\/avatar\/188bb2a69fc7e9b34a502721ee6ee3bc?s=96","billing":{"first_name":"Jos\u00e9","last_name":"Silva","company":"Empresa","address_1":"Av. Rio Branco","address_2":"Sala 805","city":"Florian\u00f3polis","state":"Santa Catarina","postcode":"88015-201","country":"Brasil","email":"jose.silva@empresa.com.br","phone":"(48) 3025-0000","number":"","neighborhood":"","persontype":"F","cpf":"","rg":"","cnpj":"","ie":"","birthdate":"","sex":"","cellphone":""},"shipping":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":"","number":"","neighborhood":""},"_links":{"self":[{"href":"https:\/\/********.com.br\/wp-json\/wc\/v1\/customers\/51"}],"collection":[{"href":"https:\/\/\/********.com.br\/wp-json\/wc\/v1\/customers"}]}}` e 

Para API v2:
`{"id":52,"date_created":"2017-06-27T00:55:06","date_created_gmt":"2017-06-27T03:55:06","date_modified":"2017-06-26T21:55:07","date_modified_gmt":"2017-06-27T00:55:07","email":"jose.silva@empresa.com.br","first_name":"Jos\u00e9","last_name":"Silva","role":"customer","username":"jose.silva","billing":{"first_name":"Jos\u00e9","last_name":"Silva","company":"Empresa","address_1":"Av. Rio Branco","address_2":"Sala 805","city":"Florian\u00f3polis","state":"Santa Catarina","postcode":"88015-201","country":"Brasil","email":"jose.silva@empresa.com.br","phone":"(48) 3025-0000","number":"","neighborhood":"","persontype":"F","cpf":"","rg":"","cnpj":"","ie":"","birthdate":"","sex":"","cellphone":""},"shipping":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":"","number":"","neighborhood":""},"is_paying_customer":false,"orders_count":0,"total_spent":"0.00","avatar_url":"https:\/\/secure.gravatar.com\/avatar\/188bb2a69fc7e9b34a502721ee6ee3bc?s=96","meta_data":[],"_links":{"self":[{"href":"https:\/\/\/********.com.br\/wp-json\/wc\/v2\/customers\/52"}],"collection":[{"href":"https:\/\/\/********.com.br\/wp-json\/wc\/v2\/customers"}]}}`

O que será que estou fazendo de errado?

Obrigado pela atenção!

Augusto Veiras

**Comment by jrbraga** [comment]
Estou tendo o mesmo problema do @claudiosanches .
QUal é a maneira correta de fazer um post para os campos do Extra Checkout Fields for Brazil 
via rest api do wocommerce. Estou usando a API mais atualizada.

**Comment by augustoveiras** [comment]
Senhores,

Consegui contornar a situação utilizando o campo "meta_data", destinado para o registro de metadados. Segue abaixo o exemplo de um registro preparado para enviar para o WooCommerce:

`var novoCliente = {
  'email': 'jose.silva@empresa.com.br',
  'password': '**********',
  'username': 'jose.silva',
  'first_name': 'José',
  'last_name': 'Silva',
  'billing' : {
    'first_name': 'José',
    'last_name': 'Silva',
    'company':'Empresa',
    'address_1':'Av. Rio Branco',
    'address_2':'Sala 805',
    'city':'Florianópolis',
    'state':'Santa Catarina',
    'postcode':'88015-201',
    'country':'BR',
    'email': 'jose.silva@empresa.com.br',
    'phone' : '(48) 3025-0000'
  },
  'meta_data' : [
    {
      'key': 'billing_persontype',
      'value': '2'
    },
    {
      'key': 'billing_cpf',
      'value' : '000.000.001-01'
    },
    {
      'key': 'billing_cnpj',
      'value': '99.888.999-0001/88'
    },
    {
      'key': 'billing_birthdate',
      'value': '01/01/1980'
    },
    {
      'key': 'billing_sex',
      'value': 'Maculino'
    },
    {
      'key': 'billing_number',
      'value': '533'
    },
    {
      'key': 'billing_neighborhood',
      'value': 'Centro'
    },
    {
      'key': 'billing_cellphone',
      'value': '(48) 99898-0000'
    }
  ]
};`

Reparem no array "meta_data" no finalzinho do registro.

Enviando desta forma, a API do WooCommerce consegue tratar os dados tranquilamente.

Espero que isso também lhe ajude aí, @jrbraga. ;)

Abraços!

**Comment by jrbraga** [comment]
Obrigado, @augustoveiras funcionou aqui também. 
Estou desenvolvendo um APP para a Hamburgueria da minha mulher, integrando o site e o PDV.
Precisando trocar figurinhas, estamos por aqui.

**Comment by claudiosanches** [comment]
Usem a última API do WooCommerce que esta documentada em https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by guilhermelirio** [comment]
Estou com esse problema. =/

**Comment by deepcell** [comment]
usando php, eu fiz dessa forma

```
			$wc_data = [
			    'email' => '',
			    'first_name' => '',
			    'last_name' => '',
			    'username' => '',
			    'password' => 'texto plano',
			    'billing' => [
			        'first_name' => '',
			        'last_name' => '',
			        'company' => '',
			        'address_1' => '',
			        'address_2' => '',
			        'city' => '',
			        'state' => '',
			        'postcode' => '',
			        'country' => 'BR',
			        'email' => '',
			        'phone' => '', 
			    ], 
		        'meta_data' => [
		        	[
		        		'key' => 'billing_persontype', 
		        		'value' => 2    // 2 = PF (CPF)
		        	], 
		        	[
		        		'key' => 'billing_cpf', 
		        		'value' => '00000000000' // sem pontuacao
		        	], 
		        ], 
			    'shipping' => [
			        'first_name' => '',
			        'last_name' => '',
			        'company' => '',
			        'address_1' => '',
			        'address_2' => '',
			        'city' => '',
			        'state' => '',
			        'postcode' => '',
			        'country' => 'BR'
			    ]
			];
			//print_r($woocommerce->post('customers', $wc_data));
			$resp_woocommerce = $woocommerce->post('customers', $wc_data);

```
