### ISSUE TITLE
Imprimir CPF em Detalhes do Cliente

### ISSUE THREAD

**Issue by tiagomspereira** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#57]
Olá!!
Eu estou montando uma loja virtual que oferece ao cliente um "cartão fidelidade", neste cartão estou imprimindo as seguintes informações:
1. Nome
2. CPF
3. Validade

Para o nome eu peguei no woocommerce da seguinte maneira:
<strong>Nome do Cliente:</strong>
		<?php
			$user = wp_get_current_user();
			?><br>
			<i><?php echo $user->user_firstname . ' ' . $user->user_lastname; ?></i>

Já funciona corretamente,
Gostaria de saber como posso fazer para que logo abaixo possa imprimir o CPF do cliente.

Desde já muito obrigado.

**Comment by claudiosanches** [comment]
Vai imprimir igual qualquer outra metadata de usuários no WordPress.

**Comment by tiagomspereira** [comment]
E como faço essa impressão?

**Comment by tiagomspereira** [comment]
Resolvi desta forma: echo get_user_meta(get_current_user_id(), 'billing_cpf', true)

**Comment by Chicodarave** [comment]
@tiagomspereira, essa linha serve no "WooCommerce PDF Invoices & Packing Slips"?
Como descubro o código (metadata?) dos outros campos?
Obrigado.
