### ISSUE TITLE
Celular no Detalhes do Pedido

### ISSUE THREAD

**Issue by atbenites** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#58]
Olá Claudio, tudo bem?

Seu plugin está me ajudando muito. 

O número do celular é um item muito importante para mim, sendo assim, deixei como preenchimento obrigatório, no entanto ele está aparecendo no Detalhes do Pedido. Como faço isso? Quais a linhas de código? Tentei fazer mas sem sucesso.

Aproveitando a oportunidade de falar com você, como faço para adicionar uma coluna com o item do pedido no Resumo do Pedido?

Obrigado.

**Comment by douglaswp** [comment]
Para exibir os itens comprados na coluna indico o plugin "**YITH Purchased Column for WooCommerce**"
Mas dependendo do caso vai causar lentidão, justo por isso essa função foi removida do Woocommerce.
