### ISSUE TITLE
Campo Bairro

### ISSUE THREAD

**Issue by dallacortx** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#59]
Gostaria de saber qual a variável ou campo do Bairro
Pois preciso puxar essa informação para outro plugin
Alguém pode me ajudar?

**Comment by andsnleo** [comment]
cara, não sei se tu já resolveu isso, mas encontrei a seguinte referência no código do plug-in. funcionou perfeitamente quando usei.

`$order->billing_neighborhood`
