### ISSUE TITLE
alterações

### ISSUE THREAD

**Issue by mitmark** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#61]
Gostaria de saber como procedo para editar o formulário de checkout abaixo:
- A configuração do telefone com 9 algarismos dá um erro e fica uma (?) antes do ultimo número.

No aguardo de uma breve resposta.

Att

**Comment by YammYcoding** [comment]
tambem quero saber

**Comment by claudiosanches** [comment]
Isso esta corrigido já.
