### ISSUE TITLE
"Nome da empresa" sempre visível no endereço de entrega

### ISSUE THREAD

**Issue by Chicodarave** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#62]
Saudações.
Percebi que não importa se selecionar pessoa física ou jurídica, o campo "Nome da empresa" está sempre visível em "Entregar para um endereço diferente?"
Está normal assim? Se não, como corrigir?

Excelente módulo BTW.

Obrigado.

PS: Para ser mais claro, é na tela de finalização de pedido, onde o cliente entra com o/s endereço/s.

**Comment by claudiosanches** [comment]
"Nome de empresa" é um campo padrão do WooCommerce, este plugin não tenta remover o campo.
