### ISSUE TITLE
Alteração de CEP

### ISSUE THREAD

**Issue by arisenna** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#63]
Tanto na tela de edição de endereço, quanto na página de checkout, caso já exista um endereço cadastrado e o usuário altere o CEP, os campos de endereço não são atualizados. Investigando o código percebi que esse comportamento está previsto na linha 190 do arquivo frontend.js

`if ( cep !== '' && 8 === cep.length && 'BR' === country && 0 === address_1.length )`

Não entendi qual a necessidade dessa implementação, se há alguma regra em outra tela que precise dessa lógica, mas pra mim não parece o ideal. O usuário que mudar de endereço não terá os dados carregados ao informar o CEP. Acho que seria melhor:

`if ( cep !== '' && 8 === cep.length && 'BR' === country )`

**Comment by claudiosanches** [comment]
Isso é feito para evitar que um erro no CEP sobrescreva todo o endereço, isso foi implementado a pedido dos usuários.
Entretanto essa opção de preenchimento de CEP esta sendo removida deste plugin e deve usar o plugin dos Correios que ainda fornece uma opção para sempre preencher os endereços como você quer.
