### ISSUE TITLE
Nota Fiscal Estadual

### ISSUE THREAD

**Issue by lguima** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#64]
Comecei a trabalhar com Wordpress e deparei-me com a necessidade de colocar uma opção no checkout para o cliente optar pela emissão da **Nota Fiscal Paulista** e, procurando o melhor lugar para adicionar, encontrei o plugin que já está instalado na loja.

Vendo que é open source, surgiu a dúvida se isso seria uma necessidade de outros também, mais alguém já precisou de algo relacionado a Nota Fiscal Estadual, seja Paulista ou alguma outra?

**Comment by renatonascalves** [comment]
Tem certeza que publicou isso no repositório correto? Esse plugin não tem relação alguma com emissão de nota fiscal. :/

**Comment by lguima** [comment]
Sim, a dúvida **não é sobre emissão de NF**, mas sobre a adição de um campo extra no checkout pro cliente optar pela emissão ou não da nota e pro lojista visualizar esta escolha e saber se emite, independente do plugin.

**Comment by renatonascalves** [comment]
Entendi! Mesmo assim, ainda não tem relação! Você deseja adicionar campos no checkout, existem plugins que fazem isso.
