### ISSUE TITLE
Bug no Layout após reordenar campos

### ISSUE THREAD

**Issue by anderbytes** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#66]
Este plugin está desorganizando alguns campos da tela de Checkout, quando algum outro plugin (Ex: WooCommerce Checkout Field Editor Pro) reordena os campos, ou muda suas posições.

Confirmei ser problema no Extra fields for Brazil, **porque quando eu desativo este plugin, tudo se organiza normalmente** num layout visualmente decente.

Segue anexo com exemplo de como está ficando quando estes dois plugins (ou outros de edição do checkout) trabalham juntos.

![bug](https://user-images.githubusercontent.com/17008092/30789325-0d61f4be-a17b-11e7-9074-9bc9e27378b3.png)

ps: o campo "Cidade" está sem ninguém à esquerda, por opção minha. O bug refere-se apenas ao campo "Número", que não obedece de forma algum o editor de campos.

**Comment by claudiosanches** [comment]
No caso não deveria estar usando em conjunto com outro plugin como "WooCommerce Checkout Field Editor Pro", se esta usando ele, deveria colocar todos os campos que você precisa direto nele.

Este plugin usa a feature de ordenação do WooCommerce 3.0 e se outro plugin tentar ordenar novamente, com certeza vai dar problema.

Basta desativar este plugin aqui então e usar apenas o outro.
