### ISSUE TITLE
Erro no Correios RESTful API

### ISSUE THREAD

**Issue by pandacreative** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#69]
GET https://correiosapi.apphb.com/cep/58050640?callback=jQuery31104881992056074229_1508288887516&_=1508288887518 net::ERR_ABORTED

Dei uma olhada no site do desenvolvedor e lá também ta com erro, mesmo os CEPS válidos retornam que o endereço não encontrado. Vocês já estão cientes disso? Abraços

**Comment by fgsants** [comment]
Alguma posição sobre esse problema?

**Comment by pandacreative** [comment]
Nada ainda =/ o erro continua.

**Comment by claudiosanches** [comment]
Essa ferramenta esta sendo removida deste plugin, é melhor usar a opção para isso que tem no plugin dos Correios que busca os CEPs no próprio Webservice dos Correios e salva no banco de dados do seu site, assim deixando mais rápido e confiável os resultados.

**Comment by claudiosanches** [comment]
Próxima versão do plugin já vou estar removendo essa ferramenta. Note que ativando a opção no plugin dos Correios já oculta essa opção.

**Comment by pandacreative** [comment]
Show Cláudio, obrigado pela resposta. Em meu site não vou utilizar PAC, SEDEX e etc, vou usar apenas a TAXA FIXA por faixa de CEP, é possível mesmo utilizando o plugin dos CORREIOS? Mais uma vez obrigado pela atenção e parabéns pela força sempre. Boa noite

**Comment by claudiosanches** [comment]
Sim, pode usar o plugin dos Correios e não adicionar nenhum método de entrega dele.
Ainda mais porque pode usar o plugin para preencher os campos no checkout e também para enviar código de rastreio para os clientes, se no caso mesmo com Taxa Fixa você use os Correios e tenha os códigos.

**Comment by pandacreative** [comment]
Na verdade vai ser motoboy, obrigado pelo esclarecimento Cláudio. Agora eu utilizando o correios e desativando o extra checkouts , mesmo assim não completa o endereço com o CEP. Estou fazendo algo errado?

**Comment by claudiosanches** [comment]
Deve funcionar agora, só se a API dos Correios caiu, o que seria muita má sorte.

**Comment by pandacreative** [comment]
Rsrsra ta bom. Muito obrigado Cláudio, uma ótima noite.
