### ISSUE TITLE
[Dúvida] Placeholder apenas em alguns campos

### ISSUE THREAD

**Issue by lguima** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#71]
Existe alguma razão para ter **placeholder** apenas em alguns campos e não em outros?

Em `includes/class-extra-checkout-fields-for-brazil-front-end.php` verifiquei que a definição do campo é diferente:

**Sem** placeholder:
```
$new_fields['billing_first_name'] = $fields['billing_first_name'];
$new_fields['billing_first_name']['class'] = array( 'form-row-first' );
$new_fields['billing_first_name']['class'] = array( 'form-row-first' );
```

**Com** placeholder:
```
$new_fields['billing_number'] = array(
    'label'       => __( 'Number', 'woocommerce-extra-checkout-fields-for-brazil' ),
    'placeholder' => _x( 'Number', 'placeholder', 'woocommerce-extra-checkout-fields-for-brazil' ),
    'class'       => array( 'form-row-first', 'address-field' ),
    'clear'       => true,
    'required'    => true,
    'priority'    => 55,
);
```

**Prints:**
![screenshot from 2017-11-01 10-12-16](https://user-images.githubusercontent.com/1562097/32274260-2fc1996c-beed-11e7-88ab-fc7034c387dd.png)
![screenshot from 2017-11-01 10-10-59](https://user-images.githubusercontent.com/1562097/32274233-058990d2-beed-11e7-8252-51b2d218f853.png)

**Comment by claudiosanches** [comment]
Sem exemplo sem placeholder é porque vêm direto do WooCommerce.
Na verdade o WooCommerce removeu alguns dos placeholders e ainda não tive tempo de fazer o mesmo neste plugin, mas devo remover no `número`, `bairro` e `celular`.
