### ISSUE TITLE
Como adicionar um requerimento de campo obrigatorio no celular ?

### ISSUE THREAD

**Issue by rhennanxkz** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#72]

**Comment by claudiosanches** [comment]
Da mesma formaque coloca campos obrigatórios em qualquer outro campo do WooCommerce.

Aqui documentação do WooCommerce: https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/

**Comment by thirodriguessp1** [comment]
@claudiosanches qual o nome do campo celular? na lista de campos do link que você enviou não vejo este campo
