### ISSUE TITLE
Incompatibilidade com Woocommerce 2.2.3

### ISSUE THREAD

**Issue by vagnervst** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#73]
## Contexto
Ao testar a integração com Wordpress 4.9.1 e Woocommerce 2.2.3, o módulo apresenta problemas na exibição dos campos.
## Atual
O campo de CPF não é inserido

![image](https://user-images.githubusercontent.com/18339615/33611792-c3d5b9ba-d9b6-11e7-8122-34d56a40b3bc.png)

## Esperado
Exibição do campo de CPF no Checkout

**Comment by claudiosanches** [comment]
`2.2.3` é bem desatualizado, desde que esta na versão 3.2.5 agora.
Recomendo você atualizar, uma vez que vai ser impossível dar suporte para qualquer versão menor do que 3 em breve.
