### ISSUE TITLE
Campos Obrigatórios Apresentam dois **

### ISSUE THREAD

**Issue by leandrotavaresrocha** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#74]
Olá,

Estou com um problema incomum com este plugin. Alguns campos como Tipo de Pessoa, CPF e RG estão apresentando dois asteriscos (**) ao invés de apenas um. Estou usando a versão 3.2.5 do woocommerce.

Obrigado.

**Comment by stefanfuchs** [comment]
Também estou com a mesma situação. Porém a loja está funcionando sem problemas, o problema é apenas visual.

**Comment by leandrotavaresrocha** [comment]
Sim, no meu caso o problema é mais visual mesmo. Aparecem dois asteriscos (**) que eu não sei por que estão aparecendo.

**Comment by claudiosanches** [comment]
Nos meus testes isso não acontece, deve ser algo no tema ou algum plugin causando isso.

**Comment by leandrotavaresrocha** [comment]
Olá Claudio,

O estranho é que este problema vem acontecendo em diversos temas que eu utilizo, praticamente este problema só não ocorre com o storefront e os twenty.

O mais engraçado é que só três campos apresentam este problema. Demais campos obrigatórios não tem isto:

![screenshot-www dungeonist com 2018 05 22 15-26-54 1](https://user-images.githubusercontent.com/5342341/40382700-6a67788e-5dd5-11e8-9c84-0b0877fdfa57.png)

**Comment by claudiosanches** [comment]
Então, bom testar com o tema ou os plugins que tem instalado, porque por padrão com o WooCommerce e um tema padrão do WordPress isso não acontece, então tem algo forçando isso novamente.

**Comment by leandrotavaresrocha** [comment]
É, eu já testei e parece ser algo relacionado aos temas. Já testei com uns cinco temas de diferentes autores e o padrão do problema se repeta. O estranho de tudo é ele adicionar o asterisco extra apenas em três campos, considerando que seu plugin introduz outros campos é estranho isto acontecer apenas aos três.

Como solução temporária, a quem possa interessar, eu adicionei uma regra de CSS: 

#billing_persontype_field > label > abbr:nth-child(2), #billing_cpf_field > label > abbr:nth-child(2), #billing_rg_field > label > abbr:nth-child(2), #billing_cnpj_field > label > abbr:nth-child(2), #billing_ie_field > label > abbr:nth-child(2)   {
	display:none;
}
