### ISSUE TITLE
Tamanho dos campos e posição no formulário

### ISSUE THREAD

**Issue by pedrouva** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#75]
Olá Claudio, tudo bem?

Estou com dificuldade de ajustar o tamanho dos campos do seu plugin. Meu conhecimento é muito básico de programação. Eu gostaria, se possível, que me ajudasse no ajuste dos campos. A página do checkout do meu tema, tem 2 colunas, e alguns campos do seu plugin, não se ajustam ao formulário e ddistorcem toda o layout da página. Vc poderia me dar alguma dica de como corrigir isso, por favor?
Segue o endereço do site da minha empresa -> https://lavanderiaumarizal.com.br/loja/pagamento/

Muito obrigado, desde já.

Pedro.

**Comment by claudiosanches** [comment]
Talvez seja melhor contratar um dev para melhorar como aparece no seu site, estou testando com os temas padrões do WordPress e com o Storefront e tudo funciona sem nenhum problema.
