### ISSUE TITLE
Bairro deveria ser campo obrigatório

### ISSUE THREAD

**Issue by stefanfuchs** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#76]
Há um problema no campo do bairro, pois não está como obrigatório e o pagar.me está dando transação não autorizada (cartão de crédito) quando o campo fica vazio. 

Corrigi o problema alterando a classe Extra_Checkout_Fields_For_Brazil_Front_End inserindo `'required'    => true` conforme abaixo. 
Caso alguém mais tenha tido esse problema, agradeço se comentarem aqui.

`		$new_fields['billing_neighborhood'] = array(
			'label'       => __( 'Neighborhood', 'woocommerce-extra-checkout-fields-for-brazil' ),
			'placeholder' => _x( 'Neighborhood', 'placeholder', 'woocommerce-extra-checkout-fields-for-brazil' ),
			'class'       => array( 'form-row-first', 'address-field' ),
			'clear'       => true,
			'required'    => true,
			'priority'    => 65,
		);
`

**Comment by douglaswp** [comment]
Algumas cidades/CEPs não tem bairro, talvez por isso não esteja obrigatório no momento.
Mas vou usar sua solução na minha loja, obrigado.

**Comment by jonatasmaxi** [comment]
Também passei por este problema por aqui. 
Acredito que uma modificação no módulo onde seja criada uma opção nas configurações na qual o cliente selecione se deseja ou não utilizar o bairro como um campo obrigatório seria o ideal.

**Comment by claudiosanches** [comment]
Muitas cidades não tem bairros, vai apenas dificultar para os clientes.
Se quer tornar obrigatório é super simples de fazer isso, tem até tutorial do WooCommerce: https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/

Se no Pagar.me é obrigatório, consigo mudar isso nele igual fiz no plugin do PagSeguro, que é bem melhor.

**Comment by mauricio-moriah** [comment]
@claudiosanches  Com o uso do plugin Extra Checkout Fields For Brazil, gera conflito com a personalização ou o uso do plugin do WooCommerce para criação de campos, e no nosso caso, o uso deste plugin se faz necessário para integração do plugin do Itau Shopline ou outros meios de pagamento, onde obriga o uso do campo Bairro.
Infelizmente como é obrigatoriedade do meio de pagamento, devemos repassar a mesma para o cliente, se não existe bairro na cidade, que use "centro" hehehe! 

Abraços.

**Comment by espimentel** [comment]
Pessoal, não sou programador e vi que esse post já é do ano passado. Mas, estou passando por um problema, que acredito que tenha relação com o campo Bairro.

Não sei aonde devo colar o código dito pelo @stefanfuchs. Você consegue me orientar?
Fui em "configurações" mas, não consegui achar uma área de código para colar esse código.

Também gostaria de escrever Bairro* (Obrigatório), hoje está escrito (Opcional), mas, dá problema quando o cliente não digita. O meu site é https://www.avidamedicina.com.br/lojinha

Obrigado pela ajuda.

**Comment by evertonstrack** [comment]
Sobre o campo bairro, o PagSeguro retorna erro quando o campo bairro não é preenchido. Estou tendo erros frequentes em pedidos por isso.
`
[body] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53060</code><message>billing address district is required.</message></error></errors>
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )
`

**Comment by gilmarscombr** [comment]
Pessoal, estou configurando o pagar.me e tive esse problema. Instalei a versão Versão 3.6.1 do plugin e resolvi da seguinte forma, editando o arquivo

wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php

declarei "required=true" na linha 361

$new_fields['shipping_neighborhood'] = array(
			'label' => __( 'Neighborhood', 'woocommerce-extra-checkout-fields-for-brazil' ),
			'class' => array( 'form-row-first', 'address-field' ),
			'clear' => true,
			'required' => true,
		);

**Comment by douglaswp** [comment]
@gilmarscombr na linha 248 também seria necessário alterar. Pois em alguns casos a entrega será feita no endereço de cobrança (depende da configuração da loja). 

Mas gostei da dica, obrigado

**Comment by gilmarscombr** [comment]
Verdade, agradeço também, e espero que tenhamos ajudado aos próximos!

**Comment by claudiosanches** [comment]
Editar os arquivos do plugin só vai gerar problema ao atualizar, acabei de fazer plugin do PagSeguro para forçar bairro, no caso do Pagar.me posso fazer o mesmo.
De qualquer forma, se for personalizar, siga o tutorial do WooCommerce: https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/
