### ISSUE TITLE
Endereço com formato inválido. Exemplo: Rua São João, 11

### ISSUE THREAD

**Issue by dgeraldinif1** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#79]
Olá,

O formulário de checkout começou a apresentar os seguintes erros impedindo a finalização da compra:

1. Endereço com formato inválido. Exemplo: Rua São João, 11
2. Por favor, preencha o bairro.
3. Telefone inválido. Preencha DDD + NÚMERO

Todos os campos estão preenchidos

O campo de endereço está preenchido apenas com o nome da rua e o campo número preenchido retorna erro. Se eu adicionar nome da rua + ", número da casa" o formulário funciona.

O campo bairro está preenchido

O campo número de telefone está preenchido com 9 dígitos. Se for preenchido com 8 o formulário funciona.

Alguém tem alguma ideia?

![screenshot_100](https://user-images.githubusercontent.com/36251619/35952598-e8dcce0e-0c67-11e8-952f-4aa3e58f5b1c.png)

**Comment by flaviotx** [comment]
To enfrentando o mesmo problema,galera vai perder venda com isso ai , muitos usuarios não vao saber finalizar o pedido.

**Comment by rhafaelcm** [comment]
Tive esse mesmo problema, e descobri que o problema está quando ativo o Plugin do Pag Seguro!
Tive que manter desativado o plugin pra parar com o erro.

**Comment by claudiosanches** [comment]
Isso parece ser problema no plugin do PagSeguro do Uol, não um problema neste plugin e nem no meu plugin do PagSeguro.
