### ISSUE TITLE
BUSCA DE CEP NÃO FUNCIONA - MÁSCARAS NÃO FUNCIONA

### ISSUE THREAD

**Issue by FBXWEB** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#82]
Olá boa noite, 

Estou com um cliente que possui o módulo instalado em uma loja WooCommerce, porém com um tema customizado (PORTO) e aparentemente seu  plugin não funciona corretamente;

Você poderia me dar uma luz para achar a solução para utilizar o seu plugin em um tema customizado??
Aguardo  seu retorno..

**Comment by claudiosanches** [comment]
Esta opção vai ser removida do plugin em breve, use a opção que tem no plugin dos Correios que é bem melhor.

**Comment by FBXWEB** [comment]
Salve Claudio, 

Obrigado pela dica companheiro, mas eu fiz uma módificação no Módulo e funcionou perfeitamente.. 

Alterei o LINK no Ajax que fazia o request para pegar os dados da busca de CEP.. Apontei para o servidor da VIACEP, depois alterei os campos de acordo com o resultado que vinha da VIACEP.. e funcionou.. 

Também adicionei uma função ao MASK.jquery para realizar a busca assim que o cep estivesse completo..
Valeu!!

**Comment by claudiosanches** [comment]
@FBXWEB não recomendo isso que você fez, já que Viacep não é dos Correios e no plugin dos Correios já busca direto no banco de dados dos próprios Correios e salva no banco de dados do seu site para consultas futuras, sendo bem mais seguro, confiável e rápido do que depender de serviço de terceiros, que foi exatamente o problema com a API que estava sendo utilizada neste plugin, além que troquei ela 3 vezes desde que criei o plugin, exatamente por esse motivo não vai ter mais essa opção neste plugin e deixar para o plugin dos Correios.

**Comment by claudiosanches** [comment]
Sem contar que quando eu fizer atualizações neste plugin você não vai mais atualizar para manter sua modificação? Mesmo que eu faça uma atualização de segurança?
