### ISSUE TITLE
woocommerce export cvs

### ISSUE THREAD

**Issue by cebellincanta** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#83]
Boa tarde,

estou suando o plugins woocommerce export, porem não estou conseguindo pegar o cpf da compra, qual nome do campo cpf?

**Comment by danielgbr** [comment]
Preciso do mesmo....

**Comment by cebellincanta** [comment]
Consegui resolver
_billing_cpf
_billing_rg
_billing_birthdate
_billing_sex
_billing_sex

**Comment by rabelo17** [comment]
Olá, boa noite.

E no caso de importar um pedido, como faço para subir as informações de CPF, RG e SEXO?
