### ISSUE TITLE
Plugin traduzido para o ingles

### ISSUE THREAD

**Issue by rotakeo** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#86]
Olá. boa tarde. O plugin funciona bem, mas não consigo ver os campos em Portugues (brasil), Não sei porque a plataforma está traduzindo os campos para o ingles.
Apesar de todas as configurações estarem para o portugues.

Poderiam me ajudar?

**Comment by claudiosanches** [comment]
Esta 100% traduzido para Português do Brasil e basta atualizar a tradução dele no painel do WordPress, igual você atualiza tradução de todos os outros plugins no menu Atualizar.
