### ISSUE TITLE
Auto-preenchimento de Rua, Bairro, Cidade, Estado por CEP parou de funcionar

### ISSUE THREAD

**Issue by govijuan** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#89]
Boa tarde Claudio.
Parabens pelo Plugin. Estou usando ele ha alguns meses mas recentemente o auto-preenchimento dos campos mencionados anteriormente por meio do CEP parou de funcionar. 

Ai dei uma pesquisada no suporte do plugin e apareceu este tópico:
https://wordpress.org/support/topic/cep-nao-autocompleta-mais/
Ali mencionaram que a API dos correios parou de funcionar e que por isso que parou de funcionar essa função do plugin. No meu browser, nas ferramentas de desenvolvedores aparece tambem este aviso: 
"Loading failed for the <script> with source “https://correiosapi.apphb.com/cep/01535001?callback=jQuery112408965627375910766_1523652348602&_=1523652348603”."

Bom eu vi que o ricocrivelli odificou o plugin chamando a api https://viacep.com.br/, por sugestão de quem criou o tópico. Dicia que essa versão estava funcionando e ofereceu o link do repositório no Github (https://github.com/ricocrivelli/woocommerce-extra-checkout-fields-for-brazil) e eu decidi dar uma olhada e testar e está funcionando.

Bom, eu queria saber se você acha que essa modficação está bem. Também queria saber se você vai trocar de API ou não. Se vai talvez possa pedr para o ricocrivelli te enviar um pull request.

Abraço

Juan

**Comment by claudiosanches** [comment]
Como expliquei em https://wordpress.org/support/topic/cep-nao-autocompleta-mais/#post-10263813

> 
> Esta opção esta sendo removida deste plugin, pois usa APIs de terceiros e nem sempre funcionam como esperado.
> Eu adicionei esse tipo de ferramenta no plugin dos Correios, lá vai buscar direto na base dos Correios e salvar o resultado no banco de dados do seu site, tornando qualquer consulta posterior mais rápida, além que é mais seguro e sempre atualizado.
> Por esse motivo recomendo parar de usar essa opção que eu devo remover até o meio do ano e começar usar a do plugin dos Correios.
