### ISSUE TITLE
mensagem (opcional) no cpf mesmo sendo obrigatório

### ISSUE THREAD

**Issue by xguiboy** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#95]
Boa tarde, na página de checkout o ao lado do CPF está aparecendo o texto (opcional) depois o asterisco de obrigatório, mas o cpf tem que ser obrigatório, como faço para tirar a mensagem de opcional?
CPF (opcional) *

**Comment by xguiboy** [comment]
desculpa, agora mesmo saiu uma atualização para corrigir esse problema, muito obrigado

**Comment by douglaswcosta** [comment]
Fala amigo, tudo bom?

Eu estava procurando essa solução mas resolvi direto no functions.php do tema;

/* Fim Campos opcionais no checkout */

add_filter( 'woocommerce_billing_fields', function( $fields ) {
    $fields['billing_neighborhood']['required'] = true;
    $fields['billing_cellphone']['required'] = true;
    $fields['billing_persontype']['required'] = true;
    $fields['billing_cpf']['required'] = true;
    $fields['billing_cnpj']['required'] = true;

    return $fields;
}, 20 );

add_filter( 'woocommerce_shipping_fields', function( $fields ) {
    $fields['shipping_neighborhood']['required'] = true;

    return $fields;
}, 20 );

/* Fim Campos opcionais no checkout */
