### ISSUE TITLE
Endereço automático do CEP

### ISSUE THREAD

**Issue by iiandrade** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#96]
Todas as requisições feitas para API de CEP está retornando 404, aparentemente, a API não funciona mais. Consequentemente os endereços não estão completando mais automaticamente!

Não seria interessante, usar outra API como: [ViaCep](https://viacep.com.br/)

**Comment by claudiosanches** [comment]
Como expliquei em https://wordpress.org/support/topic/cep-nao-autocompleta-mais/#post-10263813

> 
> Esta opção esta sendo removida deste plugin, pois usa APIs de terceiros e nem sempre funcionam como esperado.
> Eu adicionei esse tipo de ferramenta no plugin dos Correios, lá vai buscar direto na base dos Correios e salvar o resultado no banco de dados do seu site, tornando qualquer consulta posterior mais rápida, além que é mais seguro e sempre atualizado.
> Por esse motivo recomendo parar de usar essa opção que eu devo remover até o meio do ano e começar usar a do plugin dos Correios.

**Comment by josefizuda** [comment]
nem o plugin dos correios nao funciona mais

**Comment by baymabruno** [comment]
Tive que criar um plugin para fazer isso, quem quiser utilizar enquanto nada se revolve, segue o link do meu repositório

https://github.com/baymabruno/autocomplete-address-woocommerce

**Comment by mattiolix** [comment]
@baymabruno Como eu uso seu plugin? Sou novato na programaçao wordpress, nao sei onde devo colocar os arquivos. Abraços

**Comment by baymabruno** [comment]
> @baymabruno Como eu uso seu plugin? Sou novato na programaçao wordpress, nao sei onde devo colocar os arquivos. Abraços

Olá @mattiolix só baixar o zip e instalar normalmente como qualquer plugin

**Comment by XReginaldOX** [comment]
> > @baymabruno Como eu uso seu plugin? Sou novato na programaçao wordpress, nao sei onde devo colocar os arquivos. Abraços
> 
> Olá @mattiolix só baixar o zip e instalar normalmente como qualquer plugin




> Tive que criar um plugin para fazer isso, quem quiser utilizar enquanto nada se revolve, segue o link do meu repositório
> 
> https://github.com/baymabruno/autocomplete-address-woocommerce

Top seu plugin!! mas tive alguns problemas, depois de instalado o pagseguro deixou de funcionar: https://prnt.sc/vqqnxg
com o mercado pago funcionou legal mas no formulário de cadastro (checkout) a opção entregar em endereço diferente vem ativada: https://prnt.sc/vqqno7

Obrigado

**Comment by baymabruno** [comment]
> > > @baymabruno Como eu uso seu plugin? Sou novato na programaçao wordpress, nao sei onde devo colocar os arquivos. Abraços
> > 
> > 
> > Olá @mattiolix só baixar o zip e instalar normalmente como qualquer plugin
> 
> > Tive que criar um plugin para fazer isso, quem quiser utilizar enquanto nada se revolve, segue o link do meu repositório
> > https://github.com/baymabruno/autocomplete-address-woocommerce
> 
> Top seu plugin!! mas tive alguns problemas, depois de instalado o pagseguro deixou de funcionar: https://prnt.sc/vqqnxg
> com o mercado pago funcionou legal mas no formulário de cadastro (checkout) a opção entregar em endereço diferente vem ativada: https://prnt.sc/vqqno7
> 
> Obrigado

Olá @XReginaldOX, o plugin funciona por JS fazendo a busca no webservice e jogando nos campos conforme o ID padrão, se realmente mudar alguma coisa nos campos pode ocorrer problemas. Em relação a opção de entregar em endereço diferente pode ser alguma configuração do próprio woocommerce. Mas qualquer coisa pode me chamar que tento ajudar, até mesmo atualizar para alguma coisa que possa ter atualizado.
