### ISSUE TITLE
O plugin não possui um cabeçalho válido.

### ISSUE THREAD

**Issue by rfbastos** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#99]
Ao tentar ativar o plugins recebo a mensagem "O plugin não possui um cabeçalho válido."

WooCommerce Extra Checkout Fields for Brazil - Versão 3.6.1
WooCommerce - Versão 3.4.3
Wordpress - Versão 4.9.6

Na lista de Plugins o plugin aparece ativo. Porém na lista de plugins (quanto estou pesquisando plugins "woocommerce") ele aparece com o botao "Ativar"

**Comment by Jaquedeveloper** [comment]
Também tenho o mesmo problema

**Comment by claudiosanches** [comment]
Isso não acontece nas versões atuais do plugin.
